#!/usr/bin/env python3
"""Generate exact SDK operation, wire-type, and exported-Go references."""
from __future__ import annotations
import argparse, hashlib, json, os, subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'docs/sdk'
def read(name): return json.loads((ROOT/'api/openapi'/name).read_text())
def cell(value): return str(value).replace('|','\\|').replace('\n',' ')
def typename(schema):
    if '$ref' in schema: return schema['$ref'].split('/')[-1]
    if 'oneOf' in schema: return ' or '.join(typename(s) for s in schema['oneOf'])
    if 'anyOf' in schema: return ' or '.join(typename(s) for s in schema['anyOf'])
    if schema.get('type')=='array': return 'array of '+typename(schema.get('items',{}))
    if isinstance(schema.get('additionalProperties'),dict): return 'map of '+typename(schema['additionalProperties'])
    kind=schema.get('type')
    if isinstance(kind,list): return ' or '.join(kind)
    return kind or 'any JSON value'
def generate(go):
    ops=read('operations.json'); base=read('contract.base.json'); models=read('models.base.json')['components']['schemas'];ext=read('externaljobs.json')
    paths={**base['paths'],**ext['paths']}
    schemas={**models,**ext['schemas']}
    digest=hashlib.sha256(b''.join((ROOT/'api/openapi'/n).read_bytes() for n in ['operations.json','contract.base.json','models.base.json','externaljobs.json'])).hexdigest()
    intro='Generated by `python3 scripts/sdk/reference.py`. Do not edit generated tables.\n\nThese are the SDK candidate contracts. Server coverage is being implemented and qualified by operation. Consult server discovery and the implementation status for supported routes; worker execution remains a separate build and release contract. A listed SDK method is not evidence of a deployed server route. See the [guide](index.md) for runnable local examples.\n\nSchema input SHA-256: `'+digest+'`.\n'
    lines=['# SDK HTTP operation reference','',intro,'## Shared request rules','','Every method takes `context.Context` first. Authenticated v2 requests require HTTPS by default. Redirects and automatic mutation retries are disabled. `Config.AllowInsecureHTTP` explicitly permits the configured origin. Ordinary requests default to ten seconds and a 64 MiB decoded-response ceiling.','','`Response[T]` keeps `Data`, `ResourceVersion`, `RequestID`, `OperationID`, `StatusCode`, and `RetryAfter` separate. Pass the version you inspected to conditional changes. List calls default to 100 items and reject limits above 500. `Iterate` retains one page. Unknown driver observations are readable but cannot be blindly reapplied.','','Errors support `errors.Is` for conflicts, missing resources, unavailable features, expired operations, authentication, invalid input, oversized responses, and ambiguous mutations. Use `errors.As` for structured `*cpra.Error` details; avoid logging server detail or credential-bearing payloads. A cancelled wait does not cancel the server operation.','','## Operation inventory','','| SDK method | HTTP operation | Request | Response | Condition | Build |','| --- | --- | --- | --- | --- | --- |']
    for op in ops:
        condition='inspected version' if op['cas'] else ('If-None-Match: *' if op['operationID'].startswith('Create') and op['operationID']!='CreateOperation' else '—')
        lines.append('| `'+op['sdkMethod']+'` | `'+op['method']+' '+op['path']+'` | '+(op['request'] or '—')+' | '+op['schema']+' | '+condition+' | '+(op['buildTag'] or 'default')+' |')
    lines+=['','`Disable` and `Enable` are narrow conditional monitor patches. Acknowledge records who is investigating; dismiss pauses incident notifications; snooze pauses checks and notifications until its deadline. These controls have separate revision requirements. No check-now operation exists.','','## Operation parameters','']
    for op in ops:
        wire=paths[op['path']][op['method'].lower()]
        lines+=['### '+op['operationID'],'','`'+op['sdkMethod']+'` → `'+op['method']+' '+op['path']+'`','']
        params=wire.get('parameters',[])
        if params:
            lines+=['| Parameter | Location | Required | Type |','| --- | --- | --- | --- |']
            for p in params: lines.append('| `'+p['name']+'` | '+p['in']+' | '+str(p.get('required',False)).lower()+' | '+cell(typename(p.get('schema',{})))+' |')
            lines+=['']
        else: lines+=['No path, query, or header parameters beyond common authentication.','']
        if op['request']: lines+=['Body: `'+op['request']+'`. Content type: '+', '.join('`'+x+'`' for x in wire.get('requestBody',{}).get('content',{}))+'.','']
        lines+=['Response: `'+op['schema']+'`. See [wire types](wire-types.md) and [Go declarations](go-reference.md).','']
    lines+=['## Streaming Prometheus export','',f'`Client.Prometheus(ctx context.Context, w io.Writer) error` streams `GET /metrics` into a caller-owned writer. It is a handwritten helper outside the {len(ops)} generated v2 operations. The SDK closes the HTTP response body and leaves the writer open. Cancellation and the configured response-byte ceiling apply; an error can leave a partial export in the writer. Discard that partial output when the export must be complete.','','`Client.Metrics(ctx)` instead decodes the structured `GET /api/v2/metrics` response. Use it for typed observations; use `Prometheus` when you need exposition text.']
    result={'api-reference.md':'\n'.join(lines)+'\n'}
    lines=['# SDK wire types','',intro,'Optional fields use Go pointers where omission differs from an explicit zero or false. Merge patch uses JSON `null` to request deletion where permitted. Duration fields retain Go duration strings such as `60s`. Resource ID, incarnation UID, resource version, control revision, incident ID, and execution ID have different meanings; never substitute one for another.','','The descriptions below reproduce the schema contract. Inline nested shapes are included as JSON so no driver field is hidden by a summary table. `externaljobs` types are absent from default generated SDK packages.','']
    for name,schema in sorted(schemas.items()):
        lines+=['## '+name,'']
        if name not in models:lines+=['Build requirement: `externaljobs`.','']
        if schema.get('description'):lines +=[schema['description'],'']
        props=schema.get('properties',{})
        if props:
            lines+=['| Field | Required | Type | Description |','| --- | --- | --- | --- |']
            for field,s in props.items():lines.append('| `'+field+'` | '+('yes' if field in schema.get('required',[]) else 'no')+' | '+cell(typename(s))+' | '+cell(s.get('description',''))+' |')
            lines+=['']
        lines+=['```json',json.dumps(schema,indent=2,sort_keys=True),'```','']
    result['wire-types.md']='\n'.join(lines)+'\n'
    env=os.environ.copy();env.update(GOWORK='off',GOTOOLCHAIN='local')
    entries=json.loads(subprocess.check_output([go,'run',str(ROOT/'scripts/sdk/reference/main.go'),str(ROOT)],env=env,text=True,cwd=ROOT))
    exported={e['name'].lstrip('*') for e in entries if e['package']==''}
    for op in ops:
        if op['sdkMethod'] not in exported: raise ValueError('inventory names no public SDK method: '+op['sdkMethod'])
    lines=['# SDK Go declarations','',intro,'This index includes exported types, constants, errors, functions, and methods from the public SDK packages. Signatures and comments are extracted from Go syntax. Function bodies and private fields are omitted. Platform-specific implementation files may produce repeated signatures.','','The combined `api` listing includes base types plus the tagged extension. Consult [wire types](wire-types.md) for the per-type build boundary; `api` declarations that also exist in the base projection are available without `externaljobs`.','']
    package=None
    for e in entries:
        if e['package']!=package:
            package=e['package'];lines+=['## Package '+('cpra' if not package else package),'']
        lines+=['### '+e['name'],'']
        if e['tag']:lines+=['Build requirement: `externaljobs`.','']
        if e['doc']:lines +=[e['doc'].rstrip(),'']
        lines+=['```go',e['signature'],'```','']
    result['go-reference.md']='\n'.join(lines)+'\n'
    return result
def main():
    p=argparse.ArgumentParser();p.add_argument('--go',default=os.environ.get('GO','go'));p.add_argument('--check',action='store_true');args=p.parse_args()
    outputs=generate(args.go);OUT.mkdir(parents=True,exist_ok=True)
    for name,text in outputs.items():
        path=OUT/name
        if args.check:
            if not path.exists() or path.read_text()!=text:raise SystemExit('SDK reference differs: '+str(path))
        else:path.write_text(text)
    print(f'{len(outputs)} SDK references '+('verified' if args.check else 'generated'))
if __name__=='__main__':main()
