//go:build externaljobs

// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// Defines values for ActionReviewResolution.
const (
	Accepted     ActionReviewResolution = "accepted"
	Inconclusive ActionReviewResolution = "inconclusive"
	Rejected     ActionReviewResolution = "rejected"
)

// Valid indicates whether the value is a known member of the ActionReviewResolution enum.
func (e ActionReviewResolution) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Inconclusive:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for CollectionPrepareRequestIdentityFormat.
const (
	CollectionPrepareRequestIdentityFormatCpraCollectionHmacSha256JsonBytesV1 CollectionPrepareRequestIdentityFormat = "cpra.collection.hmac-sha256-json-bytes.v1"
)

// Valid indicates whether the value is a known member of the CollectionPrepareRequestIdentityFormat enum.
func (e CollectionPrepareRequestIdentityFormat) Valid() bool {
	switch e {
	case CollectionPrepareRequestIdentityFormatCpraCollectionHmacSha256JsonBytesV1:
		return true
	default:
		return false
	}
}

// Defines values for CollectionReselectionAttemptErrorCode.
const (
	AuthorizationChanged CollectionReselectionAttemptErrorCode = "authorization_changed"
	Expired              CollectionReselectionAttemptErrorCode = "expired"
	InputMismatch        CollectionReselectionAttemptErrorCode = "input_mismatch"
	OperationChanged     CollectionReselectionAttemptErrorCode = "operation_changed"
	QuotaExceeded        CollectionReselectionAttemptErrorCode = "quota_exceeded"
	StorageUnavailable   CollectionReselectionAttemptErrorCode = "storage_unavailable"
	TransferFailed       CollectionReselectionAttemptErrorCode = "transfer_failed"
	VerificationFailed   CollectionReselectionAttemptErrorCode = "verification_failed"
)

// Valid indicates whether the value is a known member of the CollectionReselectionAttemptErrorCode enum.
func (e CollectionReselectionAttemptErrorCode) Valid() bool {
	switch e {
	case AuthorizationChanged:
		return true
	case Expired:
		return true
	case InputMismatch:
		return true
	case OperationChanged:
		return true
	case QuotaExceeded:
		return true
	case StorageUnavailable:
		return true
	case TransferFailed:
		return true
	case VerificationFailed:
		return true
	default:
		return false
	}
}

// Defines values for CollectionReselectionAttemptPhase.
const (
	Completed    CollectionReselectionAttemptPhase = "completed"
	Failed       CollectionReselectionAttemptPhase = "failed"
	Transferring CollectionReselectionAttemptPhase = "transferring"
	Uploading    CollectionReselectionAttemptPhase = "uploading"
	Verified     CollectionReselectionAttemptPhase = "verified"
	Verifying    CollectionReselectionAttemptPhase = "verifying"
)

// Valid indicates whether the value is a known member of the CollectionReselectionAttemptPhase enum.
func (e CollectionReselectionAttemptPhase) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case Transferring:
		return true
	case Uploading:
		return true
	case Verified:
		return true
	case Verifying:
		return true
	default:
		return false
	}
}

// Defines values for OperationIdentityFormat.
const (
	OperationIdentityFormatCpraCollectionHmacSha256JsonBytesV1 OperationIdentityFormat = "cpra.collection.hmac-sha256-json-bytes.v1"
)

// Valid indicates whether the value is a known member of the OperationIdentityFormat enum.
func (e OperationIdentityFormat) Valid() bool {
	switch e {
	case OperationIdentityFormatCpraCollectionHmacSha256JsonBytesV1:
		return true
	default:
		return false
	}
}

// Defines values for OperationCreateRequestIdentityFormat.
const (
	OperationCreateRequestIdentityFormatCpraCollectionHmacSha256JsonBytesV1 OperationCreateRequestIdentityFormat = "cpra.collection.hmac-sha256-json-bytes.v1"
)

// Valid indicates whether the value is a known member of the OperationCreateRequestIdentityFormat enum.
func (e OperationCreateRequestIdentityFormat) Valid() bool {
	switch e {
	case OperationCreateRequestIdentityFormatCpraCollectionHmacSha256JsonBytesV1:
		return true
	default:
		return false
	}
}

// Defines values for PreflightIdentityFormat.
const (
	PreflightIdentityFormatCpraCollectionHmacSha256JsonBytesV1 PreflightIdentityFormat = "cpra.collection.hmac-sha256-json-bytes.v1"
)

// Valid indicates whether the value is a known member of the PreflightIdentityFormat enum.
func (e PreflightIdentityFormat) Valid() bool {
	switch e {
	case PreflightIdentityFormatCpraCollectionHmacSha256JsonBytesV1:
		return true
	default:
		return false
	}
}

// Defines values for PreflightRequestIdentityFormat.
const (
	PreflightRequestIdentityFormatCpraCollectionHmacSha256JsonBytesV1 PreflightRequestIdentityFormat = "cpra.collection.hmac-sha256-json-bytes.v1"
)

// Valid indicates whether the value is a known member of the PreflightRequestIdentityFormat enum.
func (e PreflightRequestIdentityFormat) Valid() bool {
	switch e {
	case PreflightRequestIdentityFormatCpraCollectionHmacSha256JsonBytesV1:
		return true
	default:
		return false
	}
}

// Defines values for ReceiptDisposition.
const (
	ReceiptDispositionAccepted  ReceiptDisposition = "accepted"
	ReceiptDispositionFinalized ReceiptDisposition = "finalized"
	ReceiptDispositionUnknown   ReceiptDisposition = "unknown"
)

// Valid indicates whether the value is a known member of the ReceiptDisposition enum.
func (e ReceiptDisposition) Valid() bool {
	switch e {
	case ReceiptDispositionAccepted:
		return true
	case ReceiptDispositionFinalized:
		return true
	case ReceiptDispositionUnknown:
		return true
	default:
		return false
	}
}

// Defines values for StartDisposition.
const (
	StartDispositionGranted  StartDisposition = "granted"
	StartDispositionPending  StartDisposition = "pending"
	StartDispositionRejected StartDisposition = "rejected"
	StartDispositionStarted  StartDisposition = "started"
	StartDispositionTerminal StartDisposition = "terminal"
	StartDispositionUnknown  StartDisposition = "unknown"
)

// Valid indicates whether the value is a known member of the StartDisposition enum.
func (e StartDisposition) Valid() bool {
	switch e {
	case StartDispositionGranted:
		return true
	case StartDispositionPending:
		return true
	case StartDispositionRejected:
		return true
	case StartDispositionStarted:
		return true
	case StartDispositionTerminal:
		return true
	case StartDispositionUnknown:
		return true
	default:
		return false
	}
}

// Defines values for StartMode.
const (
	StartModeBegin     StartMode = "begin"
	StartModeReconcile StartMode = "reconcile"
)

// Valid indicates whether the value is a known member of the StartMode enum.
func (e StartMode) Valid() bool {
	switch e {
	case StartModeBegin:
		return true
	case StartModeReconcile:
		return true
	default:
		return false
	}
}

// AccessInfo The authenticated principal and effective permissions for this request. Notification contacts are separate resources. Missing permissions never grant access.
type AccessInfo struct {
	// Permissions Explicit effective permission identifiers, exactly matching case-sensitive OpenAPI operationId values such as CreateMonitor and AcknowledgeIncident. Clients must not infer write permission solely from a role.
	Permissions []string `json:"permissions"`
	PrincipalID string   `json:"principalId"`

	// Role The named principal role: reader or operator. Future unknown roles do not implicitly grant permissions.
	Role string `json:"role"`
}

// Action defines model for Action.
type Action struct {
	// ConflictingEvidence Retained provider observation for the original execution, separate from its held outcome and operator assertion. No provider response body is included.
	ConflictingEvidence *ActionEvidence `json:"conflictingEvidence,omitempty"`
	CreatedAt           *time.Time      `json:"createdAt,omitempty"`
	ExecutionID         string          `json:"executionID,omitempty"`
	ExecutionRevision   string          `json:"executionRevision,omitempty"`

	// ExecutorFenced Whether the original executor is known finished or fenced for review.
	ExecutorFenced bool `json:"executorFenced"`

	// Held An unresolved action hold; independent of the recorded provider outcome.
	Held           bool   `json:"held"`
	ID             string `json:"id"`
	IncarnationUID string `json:"incarnationUID,omitempty"`
	IncidentID     string `json:"incidentID,omitempty"`
	Kind           string `json:"kind,omitempty"`

	// LateEvidence Retained provider observation for the original execution, separate from its held outcome and operator assertion. No provider response body is included.
	LateEvidence *ActionEvidence `json:"lateEvidence,omitempty"`
	MonitorID    string          `json:"monitorID,omitempty"`

	// Outcome Recorded provider outcome classification, unchanged by operator review.
	Outcome   string        `json:"outcome,omitempty"`
	Reason    string        `json:"reason,omitempty"`
	ReceiptID string        `json:"receiptID,omitempty"`
	Review    *ActionReview `json:"review,omitempty"`

	// ReviewRevision Opaque action observation version required for a conditional operator review.
	ReviewRevision string     `json:"reviewRevision,omitempty"`
	State          string     `json:"state"`
	UpdatedAt      *time.Time `json:"updatedAt,omitempty"`
}

// ActionEvidence Retained provider observation for the original execution, separate from its held outcome and operator assertion. No provider response body is included.
type ActionEvidence struct {
	ExecutionEnd   time.Time `json:"executionEnd"`
	ExecutionStart time.Time `json:"executionStart"`
	Outcome        string    `json:"outcome"`
	RecordedAt     time.Time `json:"recordedAt"`
}

// ActionList defines model for ActionList.
type ActionList struct {
	GeneratedAt time.Time `json:"generatedAt,omitempty"`
	Items       []Action  `json:"items"`
	NextCursor  string    `json:"nextCursor,omitempty"`
	Snapshot    string    `json:"snapshot,omitempty"`
}

// ActionReview defines model for ActionReview.
type ActionReview struct {
	Actor        string   `json:"actor"`
	Conflict     bool     `json:"conflict,omitempty"`
	EvidenceRefs []string `json:"evidenceRefs,omitempty"`

	// Note Optional operator note.
	Note       string                 `json:"note,omitempty"`
	Reason     string                 `json:"reason"`
	Resolution ActionReviewResolution `json:"resolution"`
	ReviewedAt time.Time              `json:"reviewedAt"`
	Revision   string                 `json:"revision"`
}

// ActionReviewResolution defines model for ActionReview.Resolution.
type ActionReviewResolution string

// AlertRule defines model for AlertRule.
type AlertRule struct {
	Dispatch     *bool         `json:"dispatch,omitempty"`
	Driver       *DriverConfig `json:"driver,omitempty"`
	EndpointRefs *[]string     `json:"endpointRefs,omitempty"`
	GroupRef     *string       `json:"groupRef,omitempty"`

	// NotifyType Actual notification driver key selected by the Code. Requires recipientRefs or groupRef, and excludes inline driver and direct endpointRefs.
	NotifyType    *string   `json:"notifyType,omitempty"`
	RecipientRefs *[]string `json:"recipientRefs,omitempty"`
}

// ApplyItem defines model for ApplyItem.
type ApplyItem struct {
	// ContentDigest HMAC of ordinal, identity, source coordinates and exact transmitted resource-object bytes.
	ContentDigest string `json:"contentDigest"`

	// ID Exact Kind/ID identity bound by the item MAC.
	ID       string   `json:"id"`
	Ordinal  int64    `json:"ordinal"`
	Resource Resource `json:"resource"`

	// Source Opaque ordered source token; never a filename or URL.
	Source         string `json:"source"`
	SourceDocument int64  `json:"sourceDocument"`
	SourceItem     int64  `json:"sourceItem"`
}

// ApplyResult defines model for ApplyResult.
type ApplyResult struct {
	// Applied Optional retained child observation. Absent while the accepted child is pending or when no child exists; explicit false records a terminal child that was not applied. Null is unsupported.
	Applied *bool `json:"applied,omitempty"`

	// CatalogDecision Original conditional decision: accepted, unchanged, conflict, dependencyBlocked or unattempted. A child failure never changes an accepted decision. Unknown future values remain readable.
	CatalogDecision string `json:"catalogDecision,omitempty"`

	// ChildDisposition Controller disposition of the original accepted catalog child. Never substitutes for catalogDecision and never exists for unchanged or rejected rows.
	ChildDisposition *ExecutionChildDisposition `json:"childDisposition,omitempty"`

	// Committed Optional catalog observation; true means a new mutation was accepted, false means none was accepted. Unchanged is successful without a new mutation. Omission means unavailable; null is unsupported.
	Committed *bool `json:"committed,omitempty"`

	// CommittedIndex Original decision log index; absent for an unattempted input.
	CommittedIndex *int64 `json:"committedIndex,omitempty"`

	// DecidedAt Original decision time; absent for unattempted inputs.
	DecidedAt *time.Time `json:"decidedAt,omitempty"`

	// Generation Generation produced or confirmed by the original decision.
	Generation *int64 `json:"generation,omitempty"`
	ID         string `json:"id"`

	// InputOrdinal One-based original input ordinal, defining result page order.
	InputOrdinal *int64 `json:"inputOrdinal,omitempty"`

	// Kind Resource kind for collection execution rows. Collection id retains Kind/resourceID; ordinary resource receipts retain their existing id form.
	Kind       string `json:"kind,omitempty"`
	Message    string `json:"message,omitempty"`
	NewVersion string `json:"newVersion,omitempty"`
	OldVersion string `json:"oldVersion,omitempty"`

	// OriginalUID Original incarnation from the frozen plan guard.
	OriginalUID string `json:"originalUID,omitempty"`

	// Outcome Compatibility outcome observation. For collection execution, catalogDecision and childDisposition carry separate authoritative facts. Unknown future values remain readable.
	Outcome string `json:"outcome"`

	// PlanOrdinal One-based original execution plan ordinal; independent of input order.
	PlanOrdinal *int64 `json:"planOrdinal,omitempty"`

	// Source Opaque original source token; never a source path, URL, fingerprint or key.
	Source string `json:"source,omitempty"`

	// SourceDocument One-based original source document.
	SourceDocument *int64 `json:"sourceDocument,omitempty"`

	// SourceItem One-based original source item.
	SourceItem *int64 `json:"sourceItem,omitempty"`

	// UID Incarnation produced or confirmed by the original catalog decision.
	UID string `json:"uid,omitempty"`
}

// Assignment defines model for Assignment.
type Assignment struct {
	CredentialProfile string          `json:"credentialProfile"`
	Deadline          time.Time       `json:"deadline"`
	ExecutionID       string          `json:"executionID"`
	ExecutionRevision string          `json:"executionRevision"`
	IncarnationUID    string          `json:"incarnationUID"`
	JobTypeID         string          `json:"jobTypeID"`
	JobTypeUID        string          `json:"jobTypeUID"`
	JobTypeVersion    string          `json:"jobTypeVersion"`
	Kind              string          `json:"kind"`
	LeaseID           string          `json:"leaseID"`
	MonitorID         string          `json:"monitorID"`
	Parameters        json.RawMessage `json:"parameters"`
	ServerID          string          `json:"serverID"`
	SessionID         string          `json:"sessionID"`
	WorkerUID         string          `json:"workerUID"`
}

// Assignments defines model for Assignments.
type Assignments struct {
	ClientSessionID  string       `json:"clientSessionID"`
	Items            []Assignment `json:"items"`
	PollSequence     int64        `json:"pollSequence"`
	ServerID         string       `json:"serverID"`
	SessionExpiresAt time.Time    `json:"sessionExpiresAt"`
	SessionID        string       `json:"sessionID"`
	WorkerUID        string       `json:"workerUID"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	APIVersions []string            `json:"apiVersions"`
	Drivers     map[string][]string `json:"drivers"`
	PatchTypes  []string            `json:"patchTypes"`

	// ResourceOperations Supported operations by resource; availability does not grant authorization.
	ResourceOperations map[string][]string `json:"resourceOperations,omitempty"`
	Resources          []string            `json:"resources"`
}

// CheckSpec defines model for CheckSpec.
type CheckSpec struct {
	Driver           DriverConfig `json:"driver"`
	Groups           *[]string    `json:"groups,omitempty"`
	HealthyThreshold *int64       `json:"healthyThreshold,omitempty"`

	// Interval Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	Interval    Duration `json:"interval"`
	MaxFailures *int64   `json:"maxFailures,omitempty"`
	Retries     *int64   `json:"retries,omitempty"`

	// Timeout Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	Timeout            Duration `json:"timeout"`
	UnhealthyThreshold *int64   `json:"unhealthyThreshold,omitempty"`
}

// CodeNotificationDatadog defines model for CodeNotificationDatadog.
type CodeNotificationDatadog struct {
	APIKey *string   `json:"apiKey,omitempty"`
	AppKey *string   `json:"appKey,omitempty"`
	Site   *string   `json:"site,omitempty"`
	Tags   *[]string `json:"tags,omitempty"`
	URL    *string   `json:"url,omitempty"`
}

// CodeNotificationDiscord defines model for CodeNotificationDiscord.
type CodeNotificationDiscord struct {
	WebhookURL *string `json:"webhookUrl,omitempty"`
}

// CodeNotificationEmail defines model for CodeNotificationEmail.
type CodeNotificationEmail struct {
	AllowInsecure *bool   `json:"allowInsecure,omitempty"`
	From          *string `json:"from,omitempty"`
	Server        *string `json:"server,omitempty"`
	Subject       *string `json:"subject,omitempty"`
	To            *string `json:"to,omitempty"`
}

// CodeNotificationLog defines model for CodeNotificationLog.
type CodeNotificationLog struct {
	File *string `json:"file,omitempty"`
}

// CodeNotificationMattermost defines model for CodeNotificationMattermost.
type CodeNotificationMattermost struct {
	Channel    *string `json:"channel,omitempty"`
	Username   *string `json:"username,omitempty"`
	WebhookURL *string `json:"webhookUrl,omitempty"`
}

// CodeNotificationOpsgenie defines model for CodeNotificationOpsgenie.
type CodeNotificationOpsgenie struct {
	APIKey *string `json:"apiKey,omitempty"`
	URL    *string `json:"url,omitempty"`
}

// CodeNotificationPagerDuty defines model for CodeNotificationPagerDuty.
type CodeNotificationPagerDuty struct {
	RoutingKey *string `json:"routingKey,omitempty"`
	URL        *string `json:"url,omitempty"`
}

// CodeNotificationPushover defines model for CodeNotificationPushover.
type CodeNotificationPushover struct {
	AppToken *string `json:"appToken,omitempty"`
	Expire   *int64  `json:"expire,omitempty"`
	Priority *int64  `json:"priority,omitempty"`
	Retry    *int64  `json:"retry,omitempty"`
	Sound    *string `json:"sound,omitempty"`
	Title    *string `json:"title,omitempty"`
	URL      *string `json:"url,omitempty"`
	UserKey  *string `json:"userKey,omitempty"`
}

// CodeNotificationSlack defines model for CodeNotificationSlack.
type CodeNotificationSlack struct {
	WebHook *string `json:"hook,omitempty"`
}

// CodeNotificationTeams defines model for CodeNotificationTeams.
type CodeNotificationTeams struct {
	WebhookURL *string `json:"webhookUrl,omitempty"`
}

// CodeNotificationTelegram defines model for CodeNotificationTelegram.
type CodeNotificationTelegram struct {
	BotToken *string `json:"botToken,omitempty"`
	ChatID   *string `json:"chatId,omitempty"`
	TestMode *bool   `json:"testMode,omitempty"`
	URL      *string `json:"url,omitempty"`
}

// CodeNotificationTwilio defines model for CodeNotificationTwilio.
type CodeNotificationTwilio struct {
	AccountSID *string `json:"accountSid,omitempty"`
	AuthToken  *string `json:"authToken,omitempty"`
	From       *string `json:"from,omitempty"`
	To         *string `json:"to,omitempty"`
	URL        *string `json:"url,omitempty"`
}

// CodeNotificationVictorOps defines model for CodeNotificationVictorOps.
type CodeNotificationVictorOps struct {
	EntityID        *string `json:"entityId,omitempty"`
	MessageType     *string `json:"messageType,omitempty"`
	RESTEndpointKey *string `json:"restEndpointKey,omitempty"`
	RoutingKey      *string `json:"routingKey,omitempty"`
	URL             *string `json:"url,omitempty"`
}

// CodeNotificationWebhook defines model for CodeNotificationWebhook.
type CodeNotificationWebhook struct {
	Headers *map[string]string `json:"headers,omitempty"`
	Method  *string            `json:"method,omitempty"`
	URL     *string            `json:"url,omitempty"`
}

// CollectionAdmission defines model for CollectionAdmission.
type CollectionAdmission struct {
	ExpiresAt time.Time `json:"expiresAt"`

	// Ticket Private opaque creation ticket; keep in client memory with the original frozen input and omit from diagnostics.
	Ticket string `json:"ticket"`
}

// CollectionPrepareRequest Prepare an authenticated creation ticket for one frozen collection before its first Create request. Preparing a ticket never uploads or activates resources.
type CollectionPrepareRequest struct {
	// ContentDigest Opaque keyed inventory commitment; requires the original frozen key and bytes to resume.
	ContentDigest string `json:"contentDigest"`

	// IdentityFormat Versioned commitment to exact transmitted resource-object bytes. No JSON canonicalization is performed.
	IdentityFormat CollectionPrepareRequestIdentityFormat `json:"identityFormat"`

	// IdentityKey Private per-frozen-collection HMAC key. Send only to the configured authenticated server. Never return, log or persist unencrypted.
	IdentityKey *string `json:"identityKey,omitempty"`
	ItemCount   int64   `json:"itemCount"`

	// NormalizationProfile Optional versioned raw-file normalization contract, bound to the original admission and encrypted collection identity. Omit for unprofiled or typed-resource inputs. This field alone does not enable source reselection.
	NormalizationProfile string `json:"normalizationProfile,omitempty"`

	// SourceFingerprint Private keyed source commitment. Source paths and URLs remain client-local.
	SourceFingerprint *string `json:"sourceFingerprint,omitempty"`
}

// CollectionPrepareRequestIdentityFormat Versioned commitment to exact transmitted resource-object bytes. No JSON canonicalization is performed.
type CollectionPrepareRequestIdentityFormat string

// CollectionReselectionAttempt Bounded observation of an owned, disposable source-reselection attempt. Source bytes include comments and unused text. This response contains no file names, source paths, item digests, source fingerprints, inventory keys or resource plaintext. Verification and remainder upload do not activate configuration.
type CollectionReselectionAttempt struct {
	// ErrorCode Safe failure category; contains no input text, path, provider diagnostic or private commitment.
	ErrorCode *CollectionReselectionAttemptErrorCode `json:"errorCode,omitempty"`

	// ExpiresAt Fixed attempt expiry. Reads and failed requests do not renew this deadline or the original operation.
	ExpiresAt time.Time `json:"expiresAt"`

	// ID Opaque attempt identity. This is not authorization.
	ID string `json:"id"`

	// NextOffset Next raw byte offset within nextSource; zero after all sources are complete.
	NextOffset int64 `json:"nextOffset"`

	// NextSource Next sequential source ordinal while input is incomplete; zero after all sources are complete.
	NextSource int64 `json:"nextSource"`

	// NormalizationProfile The original supported file normalization profile; no parser source, key or commitment is returned.
	NormalizationProfile string `json:"normalizationProfile"`

	// OperationID The unchanged original collection operation handle.
	OperationID string `json:"operationID"`

	// OperationUploaded Observed number of uploaded resources in the original operation; not an activation or execution count.
	OperationUploaded int64                             `json:"operationUploaded"`
	Phase             CollectionReselectionAttemptPhase `json:"phase"`
	RawBytes          int64                             `json:"rawBytes"`
	SourceCount       int64                             `json:"sourceCount"`
	SourcesCompleted  int64                             `json:"sourcesCompleted"`
}

// CollectionReselectionAttemptErrorCode Safe failure category; contains no input text, path, provider diagnostic or private commitment.
type CollectionReselectionAttemptErrorCode string

// CollectionReselectionAttemptPhase defines model for CollectionReselectionAttempt.Phase.
type CollectionReselectionAttemptPhase string

// CollectionReselectionCreateRequest Create a disposable attempt owned by the authenticated original operation owner. The explicit base file normalization profile must match the original operation. This request neither extends the original operation expiry nor creates a replacement operation. Attempts are process-local and unavailable after restart.
type CollectionReselectionCreateRequest struct {
	NormalizationProfile string `json:"normalizationProfile"`
	SourceCount          int64  `json:"sourceCount"`
}

// ControlRequest defines model for ControlRequest.
type ControlRequest struct {
	// Duration Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	Duration     Duration `json:"duration,omitempty"`
	EvidenceRefs []string `json:"evidenceRefs,omitempty"`
	IncidentID   string   `json:"incidentID,omitempty"`
	Note         string   `json:"note,omitempty"`
	Reason       string   `json:"reason,omitempty"`
	Resolution   string   `json:"resolution,omitempty"`
	Revision     string   `json:"revision"`
}

// Credential defines model for Credential.
type Credential struct {
	APIVersion string          `json:"apiVersion"`
	Kind       string          `json:"kind"`
	Metadata   Metadata        `json:"metadata"`
	Spec       CredentialSpec  `json:"spec"`
	Status     json.RawMessage `json:"status,omitempty"`
}

// CredentialList defines model for CredentialList.
type CredentialList struct {
	GeneratedAt time.Time    `json:"generatedAt,omitempty"`
	Items       []Credential `json:"items"`
	NextCursor  string       `json:"nextCursor,omitempty"`
	Snapshot    string       `json:"snapshot,omitempty"`
}

// CredentialSpec defines model for CredentialSpec.
type CredentialSpec struct {
	Description *string `json:"description,omitempty"`
	Value       *string `json:"value,omitempty"`
}

// DriverConfig defines model for DriverConfig.
type DriverConfig struct {
	Config         json.RawMessage    `json:"config"`
	CredentialRefs *map[string]string `json:"credentialRefs,omitempty"`
	Type           string             `json:"type"`
}

// Duration Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
type Duration = string

// Event defines model for Event.
type Event struct {
	ActionID string `json:"actionID,omitempty"`

	// ActionKind Original action category, when the event belongs to an action.
	ActionKind string `json:"actionKind,omitempty"`
	Actor      string `json:"actor,omitempty"`

	// Color Original notification Code, when applicable.
	Color string `json:"color,omitempty"`

	// ControlRevision Original control or incident attention revision, when applicable.
	ControlRevision string `json:"controlRevision,omitempty"`

	// Endpoint Original notification endpoint index; explicit zero is retained when applicable.
	Endpoint *int `json:"endpoint,omitempty"`

	// EvidenceRefs Opaque operator-supplied evidence references. CPRa does not fetch these references.
	EvidenceRefs []string `json:"evidenceRefs,omitempty"`

	// ExecutionRevision Original execution revision, never a configuration or control version.
	ExecutionRevision string `json:"executionRevision,omitempty"`
	ID                string `json:"id"`
	IncidentID        string `json:"incidentID,omitempty"`
	Kind              string `json:"kind"`
	MonitorID         string `json:"monitorID"`

	// Note Operator note recorded with the original audited event; never provider credentials.
	Note string `json:"note,omitempty"`

	// Outcome Recorded safe outcome classification; never a provider response body.
	Outcome string    `json:"outcome,omitempty"`
	Reason  string    `json:"reason,omitempty"`
	Time    time.Time `json:"time"`
}

// EventList defines model for EventList.
type EventList struct {
	GeneratedAt time.Time `json:"generatedAt,omitempty"`
	Items       []Event   `json:"items"`
	NextCursor  string    `json:"nextCursor,omitempty"`
	Snapshot    string    `json:"snapshot,omitempty"`
}

// ExecutionChildDisposition Controller disposition of the original accepted catalog child. Never substitutes for catalogDecision and never exists for unchanged or rejected rows.
type ExecutionChildDisposition struct {
	// InvalidatedByRestore Original explicit restore marker, distinct from ordinary supersession.
	InvalidatedByRestore string `json:"invalidatedByRestore,omitempty"`

	// OperationID Original accepted child operation handle.
	OperationID string `json:"operationID"`

	// Outcome applied, projection_failed or superseded; absent while pending.
	Outcome string `json:"outcome,omitempty"`

	// State pending, completed, failed or partial. Unknown future values are observational only.
	State string `json:"state"`

	// UpdatedAt Original retained terminal observation; absent while pending.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// ExecutionResultAvailability Separate result availability, independent of Operation.state. Omission means the server has not reported execution-result support for this operation. Errors remain typed problems.
type ExecutionResultAvailability struct {
	// Counts Scalar execution observations. Catalog acceptance and controller application are independent; explicit zero is available, omission of the entire object is unavailable.
	Counts *ExecutionResultCounts `json:"counts,omitempty"`

	// State pending: original execution or publication has not sealed; ready: immutable pages are available; expired: retained result deadline passed. Unknown values remain read-only. A canceled parent may still be pending.
	State string `json:"state"`

	// Summary Immutable original identities, terminal counters and sealed result descriptor. Presence alone never establishes availability; consult executionResult.state.
	Summary *ExecutionResultSummary `json:"summary,omitempty"`
}

// ExecutionResultCounts Scalar execution observations. Catalog acceptance and controller application are independent; explicit zero is available, omission of the entire object is unavailable.
type ExecutionResultCounts struct {
	// Accepted New catalog mutations accepted. Controller disposition does not change this count.
	Accepted int64 `json:"accepted"`

	// ChildApplied Accepted children with completed/applied evidence.
	ChildApplied int64 `json:"childApplied"`

	// ChildFailed Accepted children with failed/projection_failed evidence.
	ChildFailed int64 `json:"childFailed"`

	// ChildInvalidated Accepted children invalidated by explicit restore, separately counted.
	ChildInvalidated int64 `json:"childInvalidated"`

	// ChildPending Accepted children without a retained terminal disposition.
	ChildPending int64 `json:"childPending"`

	// ChildSuperseded Accepted children superseded independently of explicit restore.
	ChildSuperseded int64 `json:"childSuperseded"`

	// Conflicts Original conditional decisions rejected by a conflicting version or incarnation.
	Conflicts int64 `json:"conflicts"`

	// DependencyBlocked Original decisions blocked by their frozen dependencies.
	DependencyBlocked int64 `json:"dependencyBlocked"`

	// Processed Original plan decisions recorded; excludes the unattempted suffix.
	Processed int64 `json:"processed"`

	// Unattempted Original inputs never decided, certified by the final stop observation; zero while applying.
	Unattempted int64 `json:"unattempted"`

	// Unchanged Successful unchanged decisions with no new mutation or controller child.
	Unchanged int64 `json:"unchanged"`
}

// ExecutionResultSummary Immutable original identities, terminal counters and sealed result descriptor. Presence alone never establishes availability; consult executionResult.state.
type ExecutionResultSummary struct {
	// Accepted New catalog mutations accepted. Controller disposition does not change this count.
	Accepted int64 `json:"accepted"`

	// Bytes Canonical sealed item bytes.
	Bytes int64 `json:"bytes"`

	// ChildApplied Accepted children with completed/applied evidence.
	ChildApplied int64 `json:"childApplied"`

	// ChildFailed Accepted children with failed/projection_failed evidence.
	ChildFailed int64 `json:"childFailed"`

	// ChildInvalidated Accepted children invalidated by explicit restore, separately counted.
	ChildInvalidated int64 `json:"childInvalidated"`

	// ChildPending Accepted children without a retained terminal disposition.
	ChildPending int64 `json:"childPending"`

	// ChildSuperseded Accepted children superseded independently of explicit restore.
	ChildSuperseded int64 `json:"childSuperseded"`

	// Conflicts Original conditional decisions rejected by a conflicting version or incarnation.
	Conflicts int64 `json:"conflicts"`

	// DependencyBlocked Original decisions blocked by their frozen dependencies.
	DependencyBlocked int64 `json:"dependencyBlocked"`

	// Digest Canonical sealed item digest.
	Digest string `json:"digest"`

	// ExpiresAt Retained result deadline, independent of cancellation receipt expiry.
	ExpiresAt time.Time `json:"expiresAt"`

	// FinalizedAt Immutable finalization time; begins the retention cohort.
	FinalizedAt time.Time `json:"finalizedAt"`

	// ItemCount Original input count; public pages follow inputOrdinal, independently of planOrdinal.
	ItemCount int64 `json:"itemCount"`

	// Outcome Final original parent outcome: completed, partial, failed, canceled or invalidated. Unknown future values are read-only observations.
	Outcome string `json:"outcome"`

	// PlanDigest Original immutable plan digest.
	PlanDigest string `json:"planDigest"`

	// PlanID Original immutable plan identity.
	PlanID string `json:"planID"`

	// Processed Original plan decisions recorded; excludes the unattempted suffix.
	Processed int64 `json:"processed"`

	// ResultID Original activation identity; never regenerated for result publication.
	ResultID string `json:"resultID"`

	// Unattempted Original inputs never decided, certified by the final stop observation; zero while applying.
	Unattempted int64 `json:"unattempted"`

	// Unchanged Successful unchanged decisions with no new mutation or controller child.
	Unchanged int64 `json:"unchanged"`

	// UploadID Original upload identity.
	UploadID string `json:"uploadID"`
}

// Explanation defines model for Explanation.
type Explanation struct {
	Description string          `json:"description"`
	Resource    string          `json:"resource"`
	Schema      json.RawMessage `json:"schema"`
}

// ExternalConfig defines model for ExternalConfig.
type ExternalConfig struct {
	CredentialProfile string          `json:"credentialProfile,omitempty"`
	JobTypeID         string          `json:"jobTypeID"`
	Parameters        json.RawMessage `json:"parameters"`
	Version           string          `json:"version"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
	Reason  string `json:"reason,omitempty"`
}

// Health defines model for Health.
type Health struct {
	Available   bool      `json:"available"`
	GeneratedAt time.Time `json:"generatedAt,omitempty"`
	Reason      string    `json:"reason,omitempty"`
}

// HeartbeatRequest defines model for HeartbeatRequest.
type HeartbeatRequest struct {
	ExecutionID string `json:"executionID"`
	GrantID     string `json:"grantID"`
	ServerID    string `json:"serverID"`
	SessionID   string `json:"sessionID"`
	WorkerID    string `json:"workerID"`
}

// HeartbeatResponse defines model for HeartbeatResponse.
type HeartbeatResponse struct {
	Accepted    bool   `json:"accepted"`
	ExecutionID string `json:"executionID"`
	GrantID     string `json:"grantID"`
	ServerID    string `json:"serverID"`
	SessionID   string `json:"sessionID"`
	WorkerUID   string `json:"workerUID"`
}

// Incident defines model for Incident.
type Incident struct {
	AcknowledgedAt time.Time `json:"acknowledgedAt,omitempty"`
	AcknowledgedBy string    `json:"acknowledgedBy,omitempty"`
	ClosedAt       time.Time `json:"closedAt,omitempty"`
	Dismissed      bool      `json:"dismissed,omitempty"`
	ID             string    `json:"id"`
	MonitorID      string    `json:"monitorID"`
	OpenedAt       time.Time `json:"openedAt,omitempty"`
	Revision       string    `json:"revision"`
	State          string    `json:"state"`
}

// IncidentList defines model for IncidentList.
type IncidentList struct {
	GeneratedAt time.Time  `json:"generatedAt,omitempty"`
	Items       []Incident `json:"items"`
	NextCursor  string     `json:"nextCursor,omitempty"`
	Snapshot    string     `json:"snapshot,omitempty"`
}

// InterventionTargetAWS defines model for InterventionTargetAWS.
type InterventionTargetAWS struct {
	InstanceID *string `json:"instanceId,omitempty"`
	Operation  *string `json:"operation,omitempty"`
	Region     *string `json:"region,omitempty"`

	// Timeout Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	Timeout *Duration `json:"timeout,omitempty"`
	Type    *string   `json:"type,omitempty"`
}

// InterventionTargetDocker defines model for InterventionTargetDocker.
type InterventionTargetDocker struct {
	Container *string `json:"container,omitempty"`

	// Timeout Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	Timeout *Duration `json:"timeout,omitempty"`
	Type    *string   `json:"type,omitempty"`
}

// InterventionTargetKubernetes defines model for InterventionTargetKubernetes.
type InterventionTargetKubernetes struct {
	Kind           *string `json:"kind,omitempty"`
	KubeconfigPath *string `json:"kubeconfigPath,omitempty"`
	Name           *string `json:"name,omitempty"`
	Namespace      *string `json:"namespace,omitempty"`
	Replicas       *int64  `json:"replicas,omitempty"`

	// Timeout Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	Timeout *Duration `json:"timeout,omitempty"`
	Type    *string   `json:"type,omitempty"`
}

// InterventionTargetSystemd defines model for InterventionTargetSystemd.
type InterventionTargetSystemd struct {
	Mode *string `json:"mode,omitempty"`

	// Timeout Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	Timeout *Duration `json:"timeout,omitempty"`
	Type    *string   `json:"type,omitempty"`
	Unit    *string   `json:"unit,omitempty"`
}

// InterventionTargetWebhook defines model for InterventionTargetWebhook.
type InterventionTargetWebhook struct {
	Body    *string            `json:"body,omitempty"`
	Headers *map[string]string `json:"headers,omitempty"`
	Method  *string            `json:"method,omitempty"`

	// Timeout Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	Timeout *Duration `json:"timeout,omitempty"`
	Type    *string   `json:"type,omitempty"`
	URL     *string   `json:"url,omitempty"`
}

// JobType defines model for JobType.
type JobType struct {
	APIVersion string      `json:"apiVersion"`
	Kind       string      `json:"kind"`
	Metadata   Metadata    `json:"metadata"`
	Spec       JobTypeSpec `json:"spec"`
}

// JobTypeList defines model for JobTypeList.
type JobTypeList struct {
	Items      []JobType `json:"items"`
	NextCursor string    `json:"nextCursor,omitempty"`
}

// JobTypeSpec defines model for JobTypeSpec.
type JobTypeSpec struct {
	Handler         string          `json:"handler"`
	Kind            string          `json:"kind"`
	ParameterSchema json.RawMessage `json:"parameterSchema"`
	ProtocolVersion string          `json:"protocolVersion"`
	RejectionCodes  []string        `json:"rejectionCodes,omitempty"`
	ResultSchema    json.RawMessage `json:"resultSchema"`

	// Timeout Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	Timeout Duration `json:"timeout,omitempty"`
	Version string   `json:"version"`
}

// LateEvidenceRequest defines model for LateEvidenceRequest.
type LateEvidenceRequest struct {
	Data              json.RawMessage `json:"data"`
	Diagnostic        string          `json:"diagnostic"`
	Evidence          []string        `json:"evidence"`
	EvidenceID        string          `json:"evidenceID"`
	ExecutionID       string          `json:"executionID"`
	OriginalReceiptID string          `json:"originalReceiptID"`
	ServerID          string          `json:"serverID"`
	WorkerUID         string          `json:"workerUID"`
}

// MaintenanceWindow defines model for MaintenanceWindow.
type MaintenanceWindow struct {
	Cron *string `json:"cron,omitempty"`

	// Duration Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	Duration *Duration  `json:"duration,omitempty"`
	End      *time.Time `json:"end,omitempty"`
	Start    *time.Time `json:"start,omitempty"`
	Timezone *string    `json:"timezone,omitempty"`
}

// Measurement defines model for Measurement.
type Measurement struct {
	Available bool   `json:"available"`
	Reason    string `json:"reason,omitempty"`

	// Value Meaningful only when available is true; units are defined by the containing field.
	Value float64 `json:"value"`
}

// MergePatch defines model for MergePatch.
type MergePatch = json.RawMessage

// Metadata defines model for Metadata.
type Metadata struct {
	Generation      int64              `json:"generation,omitempty"`
	ID              string             `json:"id"`
	Labels          *map[string]string `json:"labels,omitempty"`
	Name            *string            `json:"name,omitempty"`
	ResourceVersion string             `json:"resourceVersion,omitempty"`
	UID             string             `json:"uid,omitempty"`
}

// Metrics defines model for Metrics.
type Metrics struct {
	GeneratedAt      time.Time `json:"generatedAt"`
	Pools            []Pool    `json:"pools,omitempty"`
	PoolsAvailable   bool      `json:"poolsAvailable"`
	Queues           []Queue   `json:"queues,omitempty"`
	QueuesAvailable  bool      `json:"queuesAvailable"`
	SLO              SLOView   `json:"slo,omitempty"`
	Systems          []System  `json:"systems,omitempty"`
	SystemsAvailable bool      `json:"systemsAvailable"`
}

// Monitor defines model for Monitor.
type Monitor struct {
	APIVersion string        `json:"apiVersion"`
	Kind       string        `json:"kind"`
	Metadata   Metadata      `json:"metadata"`
	Spec       MonitorSpec   `json:"spec"`
	Status     MonitorStatus `json:"status,omitempty"`
}

// MonitorList defines model for MonitorList.
type MonitorList struct {
	GeneratedAt time.Time `json:"generatedAt,omitempty"`
	Items       []Monitor `json:"items"`
	NextCursor  string    `json:"nextCursor,omitempty"`
	Snapshot    string    `json:"snapshot,omitempty"`
}

// MonitorSpec defines model for MonitorSpec.
type MonitorSpec struct {
	Check                 CheckSpec             `json:"check"`
	Enabled               *bool                 `json:"enabled,omitempty"`
	Maintenance           *[]MaintenanceWindow  `json:"maintenance,omitempty"`
	NotificationGroupRefs *[]string             `json:"notificationGroupRefs,omitempty"`
	Notifications         *map[string]AlertRule `json:"notifications,omitempty"`
	Recovery              *RecoverySpec         `json:"recovery,omitempty"`
	Tags                  *[]string             `json:"tags,omitempty"`
}

// MonitorStatus defines model for MonitorStatus.
type MonitorStatus struct {
	ControlRevision    string      `json:"controlRevision,omitempty"`
	ExecutionRevision  string      `json:"executionRevision,omitempty"`
	Health             string      `json:"health,omitempty"`
	IncidentID         string      `json:"incidentID,omitempty"`
	LastCheckLatencyMS Measurement `json:"lastCheckLatencyMs,omitempty"`
	LastCheckedAt      time.Time   `json:"lastCheckedAt,omitempty"`
	ObservedGeneration int64       `json:"observedGeneration,omitempty"`
	SnoozedUntil       time.Time   `json:"snoozedUntil,omitempty"`
	StatusRevision     string      `json:"statusRevision,omitempty"`
	UnknownActions     int64       `json:"unknownActions,omitempty"`
}

// NotificationEndpoint defines model for NotificationEndpoint.
type NotificationEndpoint struct {
	APIVersion string          `json:"apiVersion"`
	Kind       string          `json:"kind"`
	Metadata   Metadata        `json:"metadata"`
	Spec       DriverConfig    `json:"spec"`
	Status     json.RawMessage `json:"status,omitempty"`
}

// NotificationEndpointList defines model for NotificationEndpointList.
type NotificationEndpointList struct {
	GeneratedAt time.Time              `json:"generatedAt,omitempty"`
	Items       []NotificationEndpoint `json:"items"`
	NextCursor  string                 `json:"nextCursor,omitempty"`
	Snapshot    string                 `json:"snapshot,omitempty"`
}

// NotificationGroup defines model for NotificationGroup.
type NotificationGroup struct {
	APIVersion string   `json:"apiVersion"`
	Kind       string   `json:"kind"`
	Metadata   Metadata `json:"metadata"`

	// Spec Ordered endpoint and recipient references. At least one member is required; groups cannot contain other groups.
	Spec   NotificationGroupSpec `json:"spec"`
	Status json.RawMessage       `json:"status,omitempty"`
}

// NotificationGroupList defines model for NotificationGroupList.
type NotificationGroupList struct {
	GeneratedAt time.Time           `json:"generatedAt,omitempty"`
	Items       []NotificationGroup `json:"items"`
	NextCursor  string              `json:"nextCursor,omitempty"`
	Snapshot    string              `json:"snapshot,omitempty"`
}

// NotificationGroupSpec Ordered endpoint and recipient references. At least one member is required; groups cannot contain other groups.
type NotificationGroupSpec struct {
	EndpointRefs  []string `json:"endpointRefs,omitempty"`
	RecipientRefs []string `json:"recipientRefs,omitempty"`
}

// Operation defines model for Operation.
type Operation struct {
	// Applied Optional observed progress; omission means not reported. Explicit zero or false is retained. Null is unsupported.
	Applied *int64 `json:"applied,omitempty"`

	// Committed Optional observed progress; omission means not reported. Explicit zero or false is retained. Null is unsupported.
	Committed     *int64 `json:"committed,omitempty"`
	ContentDigest string `json:"contentDigest"`

	// ExecutionResult Separate result availability, independent of Operation.state. Omission means the server has not reported execution-result support for this operation. Errors remain typed problems.
	ExecutionResult *ExecutionResultAvailability `json:"executionResult,omitempty"`
	ID              string                       `json:"id"`

	// IdentityFormat Present for collection protocol receipts; the caller must recognize it before uploading, validating or activating.
	IdentityFormat OperationIdentityFormat `json:"identityFormat,omitempty"`

	// ItemCount Declared frozen collection size. Required by collection protocol receipts; absent for non-collection operations. Null is unsupported.
	ItemCount  *int64        `json:"itemCount,omitempty"`
	Items      []ApplyResult `json:"items,omitempty"`
	NextCursor string        `json:"nextCursor,omitempty"`

	// NormalizationProfile Original raw-file normalization contract when declared. Missing means no file profile was recorded. Unknown future values are read-only and must not be used to reinterpret the original inventory.
	NormalizationProfile string `json:"normalizationProfile,omitempty"`
	RetryAfterSeconds    int64  `json:"retryAfterSeconds,omitempty"`

	// State Parent progress/outcome. canceled and invalidated stop further decisions but do not imply executionResult.state is ready. Unknown future values remain read-only.
	State string `json:"state"`

	// Uploaded Optional observed progress; omission means not reported. Explicit zero or false is retained. Null is unsupported.
	Uploaded *int64 `json:"uploaded,omitempty"`

	// Validated Optional observed progress; omission means not reported. Explicit zero or false is retained. Null is unsupported.
	Validated *bool `json:"validated,omitempty"`
}

// OperationIdentityFormat Present for collection protocol receipts; the caller must recognize it before uploading, validating or activating.
type OperationIdentityFormat string

// OperationCreateRequest defines model for OperationCreateRequest.
type OperationCreateRequest struct {
	// AdmissionTicket Original opaque ticket returned by PrepareCollection. Keep it with the frozen input. Never replace it automatically after attempting Create. Expired or restored-epoch tickets cannot allocate new operations.
	AdmissionTicket string `json:"admissionTicket"`

	// ContentDigest Opaque keyed inventory commitment; requires the original frozen key and bytes to resume.
	ContentDigest string `json:"contentDigest"`

	// IdentityFormat Versioned commitment to exact transmitted resource-object bytes. No JSON canonicalization is performed.
	IdentityFormat OperationCreateRequestIdentityFormat `json:"identityFormat"`

	// IdentityKey Private per-frozen-collection HMAC key. Send only to the configured authenticated server. Never return, log or persist unencrypted.
	IdentityKey *string `json:"identityKey,omitempty"`
	ItemCount   int64   `json:"itemCount"`

	// NormalizationProfile Optional versioned raw-file normalization contract, bound to the original admission and encrypted collection identity. Omit for unprofiled or typed-resource inputs. This field alone does not enable source reselection.
	NormalizationProfile string `json:"normalizationProfile,omitempty"`

	// SourceFingerprint Private keyed source commitment. Source paths and URLs remain client-local.
	SourceFingerprint *string `json:"sourceFingerprint,omitempty"`
}

// OperationCreateRequestIdentityFormat Versioned commitment to exact transmitted resource-object bytes. No JSON canonicalization is performed.
type OperationCreateRequestIdentityFormat string

// OperationList defines model for OperationList.
type OperationList struct {
	GeneratedAt time.Time   `json:"generatedAt,omitempty"`
	Items       []Operation `json:"items"`
	NextCursor  string      `json:"nextCursor,omitempty"`
	Snapshot    string      `json:"snapshot,omitempty"`
}

// Outcome defines model for Outcome.
type Outcome struct {
	Data                json.RawMessage `json:"data"`
	Diagnostic          string          `json:"diagnostic"`
	DiagnosticTruncated bool            `json:"diagnosticTruncated"`
	Evidence            []string        `json:"evidence"`
	ExecutionID         string          `json:"executionID"`
	GrantID             string          `json:"grantID"`
	Kind                string          `json:"kind"`
	RejectionCode       string          `json:"rejectionCode"`
	ServerID            string          `json:"serverID"`
	Status              string          `json:"status"`
	WorkerUID           string          `json:"workerUID"`
}

// Percentiles defines model for Percentiles.
type Percentiles struct {
	Available bool    `json:"available"`
	P50MS     float64 `json:"p50Ms"`
	P95MS     float64 `json:"p95Ms"`
	P99MS     float64 `json:"p99Ms"`
}

// PollRequest defines model for PollRequest.
type PollRequest struct {
	Capabilities    []WorkerCapability `json:"capabilities"`
	Capacity        int64              `json:"capacity"`
	ClientSessionID string             `json:"clientSessionID"`
	Limit           int64              `json:"limit"`
	PollSequence    int64              `json:"pollSequence"`
	ServerID        string             `json:"serverID"`
	SessionID       string             `json:"sessionID"`
	WaitSeconds     int64              `json:"waitSeconds"`
	WorkerID        string             `json:"workerID"`
}

// Pool defines model for Pool.
type Pool struct {
	AdjustmentReason             string      `json:"adjustmentReason,omitempty"`
	Available                    bool        `json:"available"`
	Busy                         int64       `json:"busy,omitempty"`
	BusyAvailable                bool        `json:"busyAvailable"`
	Capacity                     int64       `json:"capacity"`
	LastScaleAt                  *time.Time  `json:"lastScaleAt,omitempty"`
	Maximum                      int64       `json:"maximum"`
	Minimum                      int64       `json:"minimum"`
	ModelRecommendation          int64       `json:"modelRecommendation,omitempty"`
	ModelRecommendationAvailable bool        `json:"modelRecommendationAvailable"`
	Name                         string      `json:"name"`
	PendingResults               int64       `json:"pendingResults"`
	ScalingEvents                int64       `json:"scalingEvents"`
	ServiceSamples               int64       `json:"serviceSamples"`
	ServiceTime                  Measurement `json:"serviceTime,omitempty"`
	SizingModel                  string      `json:"sizingModel"`
	SloCondition                 string      `json:"sloCondition"`
	Target                       int64       `json:"target"`
	TasksCompleted               int64       `json:"tasksCompleted"`
	TasksSubmitted               int64       `json:"tasksSubmitted"`
	WaitingTasks                 int64       `json:"waitingTasks"`

	// Workers Current worker goroutines, including idle workers; not a count of busy executions.
	Workers int64 `json:"workers"`
}

// PoolList defines model for PoolList.
type PoolList struct {
	Available   bool      `json:"available"`
	GeneratedAt time.Time `json:"generatedAt,omitempty"`
	Items       []Pool    `json:"items"`
	NextCursor  string    `json:"nextCursor,omitempty"`
	Snapshot    string    `json:"snapshot,omitempty"`
}

// Preflight defines model for Preflight.
type Preflight struct {
	ContentDigest string       `json:"contentDigest,omitempty"`
	Errors        []FieldError `json:"errors,omitempty"`

	// IdentityFormat Present for collection protocol receipts; the caller must recognize it before uploading, validating or activating.
	IdentityFormat PreflightIdentityFormat `json:"identityFormat,omitempty"`

	// ItemCount Declared frozen collection size. Required by collection protocol receipts; absent for non-collection operations. Null is unsupported.
	ItemCount *int64        `json:"itemCount,omitempty"`
	Items     []ApplyResult `json:"items,omitempty"`
	Valid     bool          `json:"valid"`
}

// PreflightIdentityFormat Present for collection protocol receipts; the caller must recognize it before uploading, validating or activating.
type PreflightIdentityFormat string

// PreflightRequest defines model for PreflightRequest.
type PreflightRequest struct {
	// ContentDigest Opaque keyed inventory commitment; requires the original frozen key and bytes to resume.
	ContentDigest string `json:"contentDigest"`

	// IdentityFormat Versioned commitment to exact transmitted resource-object bytes. No JSON canonicalization is performed.
	IdentityFormat PreflightRequestIdentityFormat `json:"identityFormat"`

	// IdentityKey Private per-frozen-collection HMAC key. Send only to the configured authenticated server. Never return, log or persist unencrypted.
	IdentityKey *string     `json:"identityKey,omitempty"`
	ItemCount   int64       `json:"itemCount"`
	Items       []ApplyItem `json:"items"`

	// SourceFingerprint Private keyed source commitment. Source paths and URLs remain client-local.
	SourceFingerprint *string `json:"sourceFingerprint,omitempty"`
}

// PreflightRequestIdentityFormat Versioned commitment to exact transmitted resource-object bytes. No JSON canonicalization is performed.
type PreflightRequestIdentityFormat string

// Problem defines model for Problem.
type Problem struct {
	Code        string       `json:"code,omitempty"`
	Detail      string       `json:"detail,omitempty"`
	Errors      []FieldError `json:"errors,omitempty"`
	Instance    string       `json:"instance,omitempty"`
	OperationID string       `json:"operationID,omitempty"`
	RequestID   string       `json:"requestID,omitempty"`
	Status      int64        `json:"status,omitempty"`
	Title       string       `json:"title,omitempty"`
	Type        string       `json:"type,omitempty"`
}

// PulseDNSConfig defines model for PulseDNSConfig.
type PulseDNSConfig struct {
	Host    *string `json:"host,omitempty"`
	Retries *int64  `json:"retries,omitempty"`
	Server  *string `json:"server,omitempty"`
}

// PulseDockerConfig defines model for PulseDockerConfig.
type PulseDockerConfig struct {
	Container *string `json:"container,omitempty"`
	Retries   *int64  `json:"retries,omitempty"`
}

// PulseGRPCConfig defines model for PulseGRPCConfig.
type PulseGRPCConfig struct {
	Host    *string `json:"host,omitempty"`
	Port    *int64  `json:"port,omitempty"`
	Retries *int64  `json:"retries,omitempty"`
	Service *string `json:"service,omitempty"`
}

// PulseHTTPConfig defines model for PulseHTTPConfig.
type PulseHTTPConfig struct {
	Body               *string            `json:"body,omitempty"`
	ExpectedStatus     *[]int64           `json:"expectedStatus,omitempty"`
	Headers            *map[string]string `json:"headers,omitempty"`
	InsecureSkipVerify *bool              `json:"insecureSkipVerify,omitempty"`
	Method             *string            `json:"method,omitempty"`
	Retries            *int64             `json:"retries,omitempty"`
	URL                *string            `json:"url,omitempty"`
}

// PulseICMPConfig defines model for PulseICMPConfig.
type PulseICMPConfig struct {
	Count     *int64  `json:"count,omitempty"`
	Host      *string `json:"host,omitempty"`
	Privilege *bool   `json:"ignorePrivilege,omitempty"`
	Retries   *int64  `json:"retries,omitempty"`
}

// PulseKafkaConfig defines model for PulseKafkaConfig.
type PulseKafkaConfig struct {
	Brokers *[]string `json:"brokers,omitempty"`
	Retries *int64    `json:"retries,omitempty"`
}

// PulseMongoConfig defines model for PulseMongoConfig.
type PulseMongoConfig struct {
	Retries *int64  `json:"retries,omitempty"`
	URI     *string `json:"uri,omitempty"`
}

// PulseMySQLConfig defines model for PulseMySQLConfig.
type PulseMySQLConfig struct {
	Database *string `json:"database,omitempty"`
	DSN      *string `json:"dsn,omitempty"`
	Host     *string `json:"host,omitempty"`
	Password *string `json:"password,omitempty"`
	Port     *int64  `json:"port,omitempty"`
	Retries  *int64  `json:"retries,omitempty"`
	User     *string `json:"user,omitempty"`
}

// PulsePostgresConfig defines model for PulsePostgresConfig.
type PulsePostgresConfig struct {
	Database *string `json:"database,omitempty"`
	DSN      *string `json:"dsn,omitempty"`
	Host     *string `json:"host,omitempty"`
	Password *string `json:"password,omitempty"`
	Port     *int64  `json:"port,omitempty"`
	Retries  *int64  `json:"retries,omitempty"`
	SSLMode  *string `json:"sslmode,omitempty"`
	User     *string `json:"user,omitempty"`
}

// PulseRabbitMQConfig defines model for PulseRabbitMQConfig.
type PulseRabbitMQConfig struct {
	Retries *int64  `json:"retries,omitempty"`
	URL     *string `json:"url,omitempty"`
}

// PulseRedisConfig defines model for PulseRedisConfig.
type PulseRedisConfig struct {
	Addr     *string `json:"addr,omitempty"`
	DB       *int64  `json:"db,omitempty"`
	Password *string `json:"password,omitempty"`
	Retries  *int64  `json:"retries,omitempty"`
	Username *string `json:"username,omitempty"`
}

// PulseTCPConfig defines model for PulseTCPConfig.
type PulseTCPConfig struct {
	Host    *string `json:"host,omitempty"`
	Port    *int64  `json:"port,omitempty"`
	Retries *int64  `json:"retries,omitempty"`
}

// PulseTLSConfig defines model for PulseTLSConfig.
type PulseTLSConfig struct {
	CriticalDays       *int64  `json:"criticalDays,omitempty"`
	Host               *string `json:"host,omitempty"`
	InsecureSkipVerify *bool   `json:"insecureSkipVerify,omitempty"`
	Port               *int64  `json:"port,omitempty"`
	Retries            *int64  `json:"retries,omitempty"`
	ServerName         *string `json:"serverName,omitempty"`
	WarnDays           *int64  `json:"warnDays,omitempty"`
}

// PulseUDPConfig defines model for PulseUDPConfig.
type PulseUDPConfig struct {
	Host    *string `json:"host,omitempty"`
	Payload *string `json:"payload,omitempty"`
	Port    *int64  `json:"port,omitempty"`
	Retries *int64  `json:"retries,omitempty"`
}

// Queue defines model for Queue.
type Queue struct {
	Available   bool        `json:"available"`
	AverageWait Measurement `json:"averageWait,omitempty"`
	Capacity    int64       `json:"capacity"`

	// CompletedPerSecond Absent when completed-execution rate is not measured; consult completedRateAvailable.
	CompletedPerSecond     float64 `json:"completedPerSecond,omitempty"`
	CompletedRateAvailable bool    `json:"completedRateAvailable"`
	Depth                  int64   `json:"depth"`

	// DequeuedPerSecond Dequeued jobs per second; this is not a completed-execution rate.
	DequeuedPerSecond float64     `json:"dequeuedPerSecond"`
	Drops             int64       `json:"drops"`
	EnqueuedPerSecond float64     `json:"enqueuedPerSecond"`
	LimitReason       string      `json:"limitReason,omitempty"`
	MaximumWait       Measurement `json:"maximumWait,omitempty"`
	Name              string      `json:"name"`
	OldestPendingMS   Measurement `json:"oldestPendingMs,omitempty"`
	RatesAvailable    bool        `json:"ratesAvailable"`

	// SampleWindow Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	SampleWindow Duration    `json:"sampleWindow,omitempty"`
	Saturated    bool        `json:"saturated"`
	Utilization  Measurement `json:"utilization,omitempty"`
}

// QueueList defines model for QueueList.
type QueueList struct {
	Available   bool      `json:"available"`
	GeneratedAt time.Time `json:"generatedAt,omitempty"`
	Items       []Queue   `json:"items"`
	NextCursor  string    `json:"nextCursor,omitempty"`
	Snapshot    string    `json:"snapshot,omitempty"`
}

// Receipt defines model for Receipt.
type Receipt struct {
	Disposition ReceiptDisposition `json:"disposition"`
	ExecutionID string             `json:"executionID"`
	ReceiptID   string             `json:"receiptID"`
	ServerID    string             `json:"serverID"`
	WorkerUID   string             `json:"workerUID"`
}

// ReceiptDisposition defines model for ReceiptDisposition.
type ReceiptDisposition string

// Recipient defines model for Recipient.
type Recipient struct {
	APIVersion string   `json:"apiVersion"`
	Kind       string   `json:"kind"`
	Metadata   Metadata `json:"metadata"`

	// Spec A notification contact with ordered references to typed notification endpoints; not an authentication principal.
	Spec   RecipientSpec   `json:"spec"`
	Status json.RawMessage `json:"status,omitempty"`
}

// RecipientList defines model for RecipientList.
type RecipientList struct {
	GeneratedAt time.Time   `json:"generatedAt,omitempty"`
	Items       []Recipient `json:"items"`
	NextCursor  string      `json:"nextCursor,omitempty"`
	Snapshot    string      `json:"snapshot,omitempty"`
}

// RecipientSpec A notification contact with ordered references to typed notification endpoints; not an authentication principal.
type RecipientSpec struct {
	EndpointRefs []string `json:"endpointRefs"`
}

// RecoverySpec defines model for RecoverySpec.
type RecoverySpec struct {
	// Cooldown Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	Cooldown    *Duration    `json:"cooldown,omitempty"`
	Driver      DriverConfig `json:"driver"`
	MaxAttempts *int64       `json:"maxAttempts,omitempty"`
	MaxFailures *int64       `json:"maxFailures,omitempty"`
	Retries     *int64       `json:"retries,omitempty"`
}

// Resource defines model for Resource.
type Resource struct {
	APIVersion string          `json:"apiVersion"`
	Kind       string          `json:"kind"`
	Metadata   Metadata        `json:"metadata"`
	Spec       json.RawMessage `json:"spec"`
	Status     json.RawMessage `json:"status,omitempty"`
}

// RuntimeConfig defines model for RuntimeConfig.
type RuntimeConfig struct {
	Available bool `json:"available"`

	// HistoryRetention Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	HistoryRetention Duration `json:"historyRetention,omitempty"`
	QueueCapacity    int64    `json:"queueCapacity,omitempty"`

	// QueueTarget Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	QueueTarget Duration `json:"queueTarget,omitempty"`
	ReadOnly    bool     `json:"readOnly"`

	// ResultTarget Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	ResultTarget Duration `json:"resultTarget,omitempty"`

	// SloWindow Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	SloWindow   Duration `json:"sloWindow,omitempty"`
	StorageMode string   `json:"storageMode,omitempty"`
}

// SLOReport defines model for SLOReport.
type SLOReport struct {
	// Attainment Compatibility alias for resultAttainment, a fraction from 0 to 1; unavailable when no expectations were recorded.
	Attainment Measurement `json:"attainment,omitempty"`
	Condition  string      `json:"condition,omitempty"`
	Driver     string      `json:"driver"`
	Execution  Percentiles `json:"execution,omitempty"`
	Expected   int64       `json:"expected"`
	Missed     int64       `json:"missed"`
	Overdue    int64       `json:"overdue"`

	// PausedMonitorSeconds Intentional pause exposure inside this rolling window, in monitor-seconds; this is a gauge, not a monotonic counter.
	PausedMonitorSeconds float64 `json:"pausedMonitorSeconds"`

	// PausedMonitors Current owner-observed intentionally paused monitor count; not missed checks.
	PausedMonitors       int64       `json:"pausedMonitors"`
	Pending              int64       `json:"pending"`
	Pipeline             string      `json:"pipeline"`
	QueueAttainment      Measurement `json:"queueAttainment,omitempty"`
	QueueDelay           Percentiles `json:"queueDelay,omitempty"`
	QueueThresholdPassed int64       `json:"queueThresholdPassed"`
	ResultAttainment     Measurement `json:"resultAttainment,omitempty"`
	Samples              int64       `json:"samples"`
	Timeouts             int64       `json:"timeouts"`
	TotalLatency         Percentiles `json:"totalLatency,omitempty"`
	TotalThresholdPassed int64       `json:"totalThresholdPassed"`
}

// SLOView defines model for SLOView.
type SLOView struct {
	Available      bool        `json:"available"`
	CoverageGap    bool        `json:"coverageGap"`
	GapEnd         *time.Time  `json:"gapEnd,omitempty"`
	GapStart       *time.Time  `json:"gapStart,omitempty"`
	GeneratedAt    time.Time   `json:"generatedAt"`
	QueueTargetMS  float64     `json:"queueTargetMs"`
	Reports        []SLOReport `json:"reports"`
	ResultTargetMS float64     `json:"resultTargetMs"`

	// Window Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.
	Window Duration `json:"window"`
}

// StartDisposition defines model for StartDisposition.
type StartDisposition string

// StartMode defines model for StartMode.
type StartMode string

// StartRequest defines model for StartRequest.
type StartRequest struct {
	ExecutionID       string    `json:"executionID"`
	ExecutionRevision string    `json:"executionRevision"`
	LeaseID           string    `json:"leaseID"`
	Mode              StartMode `json:"mode"`
	ServerID          string    `json:"serverID"`
	SessionID         string    `json:"sessionID"`
}

// StartResponse Only granted from the original live begin permits invocation. Reconcile never grants. Other dispositions report original attempt state with conditional grant and receipt fields.
type StartResponse struct {
	Deadline          time.Time        `json:"deadline"`
	Disposition       StartDisposition `json:"disposition"`
	ExecutionID       string           `json:"executionID"`
	ExecutionRevision string           `json:"executionRevision"`
	GrantID           string           `json:"grantID"`
	LeaseID           string           `json:"leaseID"`
	ReceiptID         string           `json:"receiptID"`
	ServerID          string           `json:"serverID"`
	SessionID         string           `json:"sessionID"`
	WorkerUID         string           `json:"workerUID"`
}

// State defines model for State.
type State struct {
	Actions                 []Action     `json:"actions,omitempty"`
	ControllerAvailable     bool         `json:"controllerAvailable"`
	ControllerReady         bool         `json:"controllerReady"`
	ControllerReason        string       `json:"controllerReason"`
	GeneratedAt             time.Time    `json:"generatedAt"`
	Live                    bool         `json:"live"`
	ProjectionAgeMS         float64      `json:"projectionAgeMs,omitempty"`
	ProjectionAvailable     bool         `json:"projectionAvailable"`
	ProjectionFresh         bool         `json:"projectionFresh"`
	ReadinessReason         string       `json:"readinessReason,omitempty"`
	Ready                   bool         `json:"ready"`
	Storage                 StorageState `json:"storage"`
	UnknownActions          int64        `json:"unknownActions,omitempty"`
	UnknownActionsAvailable bool         `json:"unknownActionsAvailable"`
}

// StorageState defines model for StorageState.
type StorageState struct {
	AppliedIndex int64 `json:"appliedIndex"`

	// Available Current durable-store observation.
	Available      bool  `json:"available"`
	Bytes          int64 `json:"bytes,omitempty"`
	BytesAvailable bool  `json:"bytesAvailable"`

	// CommitIndex Compatibility observation of the FSM-applied log index; not an independently sampled Raft commit index.
	CommitIndex   int64       `json:"commitIndex,omitempty"`
	CommitLatency Measurement `json:"commitLatency,omitempty"`
	Error         string      `json:"error,omitempty"`

	// FormatVersion Current application snapshot format, distinct from node identity and authentication format versions.
	FormatVersion int64  `json:"formatVersion,omitempty"`
	Mode          string `json:"mode"`

	// SingleNode Current durable-store observation.
	SingleNode       bool        `json:"singleNode"`
	SnapshotDuration Measurement `json:"snapshotDuration,omitempty"`
}

// System defines model for System.
type System struct {
	Available             bool        `json:"available"`
	AverageUpdateDuration Measurement `json:"averageUpdateDuration,omitempty"`
	EntitiesProcessed     int64       `json:"entitiesProcessed"`
	LastUpdateDurationMS  Measurement `json:"lastUpdateDurationMs,omitempty"`
	MaximumUpdateDuration Measurement `json:"maximumUpdateDuration,omitempty"`
	MinimumUpdateDuration Measurement `json:"minimumUpdateDuration,omitempty"`
	Name                  string      `json:"name"`
	ProgressAt            *time.Time  `json:"progressAt,omitempty"`
	Updates               int64       `json:"updates"`
}

// SystemList defines model for SystemList.
type SystemList struct {
	Available   bool      `json:"available"`
	GeneratedAt time.Time `json:"generatedAt,omitempty"`
	Items       []System  `json:"items"`
	NextCursor  string    `json:"nextCursor,omitempty"`
	Snapshot    string    `json:"snapshot,omitempty"`
}

// UploadRequest defines model for UploadRequest.
type UploadRequest struct {
	Items []ApplyItem `json:"items"`
}

// ValidationResultItem Retained, safe validation metadata in original input order. Contains no resource bodies or credentials.
type ValidationResultItem struct {
	// Change Known changes: create, update, unchanged. Unknown values are read-only observations.
	Change string `json:"change,omitempty"`
	ID     string `json:"id"`

	// Issue Allowlisted issue code, never a provider diagnostic or source path. Unknown codes are read-only observations.
	Issue           string `json:"issue,omitempty"`
	Kind            string `json:"kind"`
	Ordinal         int64  `json:"ordinal"`
	ResourceVersion string `json:"resourceVersion,omitempty"`

	// Source Opaque ordered source token; never a filename or URL.
	Source         string `json:"source"`
	SourceDocument int64  `json:"sourceDocument"`
	SourceItem     int64  `json:"sourceItem"`
	UID            string `json:"uid,omitempty"`
}

// ValidationResultPage A bounded page from one sealed validation result. Pending validation is a problem response, never valid=false. At most 4 MiB encoded response; default 100 rows, maximum 500.
type ValidationResultPage struct {
	ContentDigest  string                 `json:"contentDigest"`
	IdentityFormat string                 `json:"identityFormat"`
	ItemCount      int64                  `json:"itemCount"`
	Items          []ValidationResultItem `json:"items"`
	NextCursor     string                 `json:"nextCursor,omitempty"`
	OperationID    string                 `json:"operationID"`

	// Summary Immutable original validation verdict. Count is retained result rows, distinct from declared input itemCount. A successful plan is not permission to execute.
	Summary ValidationResultSummary `json:"summary"`
}

// ValidationResultSummary Immutable original validation verdict. Count is retained result rows, distinct from declared input itemCount. A successful plan is not permission to execute.
type ValidationResultSummary struct {
	CapabilitiesDigest string    `json:"capabilitiesDigest"`
	Count              int64     `json:"count"`
	Digest             string    `json:"digest"`
	ExpiresAt          time.Time `json:"expiresAt"`
	FinalizedAt        time.Time `json:"finalizedAt"`
	Issue              string    `json:"issue,omitempty"`
	PlanDigest         string    `json:"planDigest,omitempty"`
	PlanID             string    `json:"planID,omitempty"`
	ResultID           string    `json:"resultID"`
	SummaryOnly        bool      `json:"summaryOnly"`
	Valid              bool      `json:"valid"`
}

// Version defines model for Version.
type Version struct {
	Commit        string    `json:"commit,omitempty"`
	GoVersion     string    `json:"goVersion,omitempty"`
	SourceTime    time.Time `json:"sourceTime,omitempty"`
	StorageFormat int64     `json:"storageFormat,omitempty"`
	Version       string    `json:"version"`
}

// WorkerCapability defines model for WorkerCapability.
type WorkerCapability struct {
	JobTypeID string `json:"jobTypeID"`
	Kind      string `json:"kind"`
	Version   string `json:"version"`
}

// WorkerObservation defines model for WorkerObservation.
type WorkerObservation struct {
	Active     int64     `json:"active"`
	Capacity   int64     `json:"capacity"`
	LastSeenAt time.Time `json:"lastSeenAt"`
	WorkerID   string    `json:"workerID"`
}

// WorkerObservationList defines model for WorkerObservationList.
type WorkerObservationList struct {
	Items      []WorkerObservation `json:"items"`
	NextCursor string              `json:"nextCursor,omitempty"`
}
