#!/usr/bin/env python3
"""Generate shared palette assets; optionally render icons and sync a docs checkout."""
import argparse
import json
from pathlib import Path
import re
import shutil
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
BRAND = ROOT / 'brand'
PALETTE = json.loads((BRAND / 'palette.json').read_text())


def css():
    blocks = ['/* Generated from brand/palette.json by scripts/brand/generate.py. */']
    for mode, selector in (
        ('light', ':root, [data-theme="light"], [data-md-color-scheme="default"]'),
        ('dark', '[data-theme="dark"], [data-md-color-scheme="slate"]'),
    ):
        values = []
        for role, value in PALETTE[mode].items():
            name = re.sub(r'[A-Z]', lambda m: '-' + m.group().lower(), role)
            values.append(f'  --cpra-{name}: {value};')
        blocks.append(selector + ' {\n' + '\n'.join(values) + '\n}')
    return '\n'.join(blocks) + '\n'


def bootstrap():
    colors = json.dumps({mode: values['canvas'] for mode, values in PALETTE.items()})
    return '''// Generated by scripts/brand/generate.py. Apply appearance before the first paint.
(() => {
  let preference = 'system';
  try {
    const stored = localStorage.getItem('cpra-theme');
    if (stored === 'dark' || stored === 'light') preference = stored;
  } catch { /* System appearance also works without storage. */ }
  const dark = typeof matchMedia === 'function' && matchMedia('(prefers-color-scheme: dark)').matches;
  const theme = preference === 'system' ? (dark ? 'dark' : 'light') : preference;
  document.documentElement.dataset.theme = theme;
  const colors = ''' + colors + ''';
  document.querySelector('meta[name="theme-color"]')?.setAttribute('content', colors[theme]);
})();
'''


def render_images():
    import cairosvg
    cairosvg.svg2png(url=str(BRAND / 'src/social-preview.svg'),
                    write_to=str(BRAND / 'dist/png/social-preview.png'))
    namespace = 'http://www.w3.org/2000/svg'
    ET.register_namespace('', namespace)
    for filename, size, mark_size in [('apple-touch-icon.png', 180, 140), ('icon-mask.png', 512, 380)]:
        svg = ET.Element(f'{{{namespace}}}svg', width=str(size), height=str(size), viewBox=f'0 0 {size} {size}')
        ET.SubElement(svg, f'{{{namespace}}}rect', width=str(size), height=str(size), fill=PALETTE['light']['canvas'])
        offset = (size - mark_size) / 2
        group = ET.SubElement(svg, f'{{{namespace}}}g', transform=f'translate({offset} {offset}) scale({mark_size / 64})')
        group.extend(ET.parse(BRAND / 'dist/svg/cpra-mark-color.svg').getroot())
        cairosvg.svg2png(bytestring=ET.tostring(svg), write_to=str(BRAND / 'dist/favicon' / filename))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail if generated text assets are stale')
    parser.add_argument('--images', action='store_true', help='render opaque PNGs (requires cairosvg)')
    parser.add_argument('--docs-root', type=Path, help='sync assets to an existing gh-pages checkout')
    args = parser.parse_args()
    if args.check and (args.images or args.docs_root):
        parser.error('--check cannot modify images or documentation')
    outputs = {
        BRAND / 'dist/palette.css': css(),
        ROOT / 'dashboard/public/theme.js': bootstrap(),
        ROOT / 'dashboard/public/theme.css': (
            '/* Generated from brand/palette.json. Initial loading surface. */\n'
            f'html {{ background: {PALETTE["light"]["canvas"]}; color-scheme: light; }}\n'
            f'html[data-theme="dark"] {{ background: {PALETTE["dark"]["canvas"]}; color-scheme: dark; }}\n'
            'body { margin: 0; }\n#root { min-height: 100vh; }\n'
        ),
    }
    stale = []
    for path, text in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if args.check:
        if stale:
            raise SystemExit('Run python3 scripts/brand/generate.py: ' + ', '.join(stale))
        print('Shared palette and initial theme assets are current.')
        return
    if args.images:
        render_images()
    for path in (BRAND / 'dist/favicon').iterdir():
        if path.is_file():
            shutil.copyfile(path, ROOT / 'dashboard/public' / path.name)
    if args.docs_root:
        docs = args.docs_root.resolve() / '_sources/docs'
        if not docs.is_dir():
            parser.error('--docs-root must contain _sources/docs')
        shutil.copyfile(BRAND / 'dist/palette.css', docs / 'assets/stylesheets/palette.css')
        shutil.copyfile(BRAND / 'dist/png/social-preview.png', docs / 'images/social-preview.png')
        for path in (BRAND / 'dist/favicon').iterdir():
            if path.is_file():
                shutil.copyfile(path, docs / path.name)
    print('Generated palette and synchronized brand assets.')


if __name__ == '__main__':
    main()
