package management

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/ziad-hsn/cpra/internal/persistence"
	"github.com/ziad-hsn/cpra/sdk/go/collection"
)

var (
	ErrReselectionNotFound = errors.New("collection reselection attempt unavailable")
	ErrReselectionConflict = errors.New("collection reselection phase or input changed")
	ErrReselectionBusy     = errors.New("collection reselection capacity unavailable")
)

const (
	reselectionAttemptLifetime = 15 * time.Minute
	reselectionWorkTimeout     = 2 * time.Minute
	reselectionAttemptBytes    = 600 << 20
	reselectionManagerBytes    = 2 << 30
)

// CollectionReselectionStatus contains only original-operation progress and
// disposable attempt coordinates. It contains no source or inventory digests.
type CollectionReselectionStatus struct {
	ID, OperationID, NormalizationProfile, Phase, ErrorCode string
	SourceCount, SourcesCompleted, NextSource               int
	RawBytes, NextOffset, OperationUploaded                 int64
	ExpiresAt                                               time.Time
}

type collectionReselectionAttempt struct {
	*collectionReselectionAttemptState
}

type collectionReselectionAttemptState struct {
	mu               *sync.Mutex
	status           CollectionReselectionStatus
	head             persistence.CollectionState
	view             *persistence.CollectionUploadView
	authority        persistence.OperatorAuthority
	spool            *reselectionSpool
	sources          *reselectionSources
	proof            *collectionReselectionProof
	transfer         *collectionReselectionTransfer
	cancel           context.CancelFunc
	discarded, ready bool
}

// CollectionReselectionManager owns disposable attempts for one running
// Catalog. It never serializes their keys or resumes a previous process's work.
// Callers authenticate and authorize the actor before calling any method.
type CollectionReselectionManager struct {
	*collectionReselectionManagerState
}

// Value formatters must redact values as well as pointers. Keeping mutable
// fields behind one stable pointer prevents their autogenerated pointer wrappers
// from racing with live state when they copy the formatter's value receiver.
type collectionReselectionManagerState struct {
	mu         *sync.Mutex
	catalog    *Catalog
	root       *reselectionSpoolRoot
	ctx        context.Context
	cancel     context.CancelFunc
	now        func() time.Time
	attempts   map[string]*collectionReselectionAttempt
	lastCreate map[string]time.Time
	workers    chan struct{}
	closing    bool
	reserved   int64
	wg         *sync.WaitGroup
	done       chan struct{}
	closeErr   error
	cleanup    func(*reselectionSpoolRoot) error
}

func (CollectionReselectionManager) String() string               { return "collection reselection manager" }
func (m CollectionReselectionManager) GoString() string           { return m.String() }
func (m CollectionReselectionManager) Format(w fmt.State, _ rune) { _, _ = w.Write([]byte(m.String())) }
func (CollectionReselectionManager) MarshalJSON() ([]byte, error) { return nil, ErrReselectionNotFound }
func (collectionReselectionAttempt) String() string               { return "private collection reselection attempt" }
func (a collectionReselectionAttempt) GoString() string           { return a.String() }
func (a collectionReselectionAttempt) Format(w fmt.State, _ rune) { _, _ = w.Write([]byte(a.String())) }
func (collectionReselectionAttempt) MarshalJSON() ([]byte, error) { return nil, ErrReselectionNotFound }

// parent must be an application-owned private directory. The fixed child and
// its OS lock belong to this manager until Wait completes, including shutdown
// deadline expiry. Logical reservations bound file bytes, not physical blocks.
func NewCollectionReselectionManager(ctx context.Context, catalog *Catalog, parent string, now func() time.Time) (*CollectionReselectionManager, error) {
	return newCollectionReselectionManager(ctx, catalog, parent, now, nil)
}

// cleanup belongs to this owner only after successful construction. It runs
// after every borrower joins and the spool root closes, before Done closes.
// The caller retains cleanup responsibility if construction fails.
func newCollectionReselectionManager(ctx context.Context, catalog *Catalog, parent string, now func() time.Time, cleanup func(*reselectionSpoolRoot) error) (*CollectionReselectionManager, error) {
	if ctx == nil || catalog == nil || now == nil {
		return nil, ErrValidation
	}
	if err := catalog.readyContext(ctx); err != nil {
		return nil, err
	}
	root, err := newReselectionSpoolRoot(ctx, parent, reselectionSpoolRootOptions{MaxSpools: 4, MaxCleanupEntries: 64, MaxCleanupBytes: 8 << 30})
	if err != nil {
		return nil, err
	}
	owned, cancel := context.WithCancel(ctx)
	m := &CollectionReselectionManager{collectionReselectionManagerState: &collectionReselectionManagerState{mu: new(sync.Mutex), wg: new(sync.WaitGroup), catalog: catalog, root: root, ctx: owned, cancel: cancel, now: now, attempts: make(map[string]*collectionReselectionAttempt), lastCreate: make(map[string]time.Time), workers: make(chan struct{}, 2), done: make(chan struct{}), cleanup: cleanup}}
	m.wg.Add(1) // Done includes the expiration loop, not only accepted work.
	go m.expireLoop()
	return m, nil
}

func (m *CollectionReselectionManager) begin() error {
	if m == nil || m.collectionReselectionManagerState == nil || m.mu == nil {
		return ErrUnavailable
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.closing || m.ctx.Err() != nil {
		return ErrUnavailable
	}
	m.wg.Add(1)
	return nil
}

func (m *CollectionReselectionManager) BeginStop() {
	if m == nil || m.collectionReselectionManagerState == nil || m.mu == nil {
		return
	}
	m.mu.Lock()
	if m.closing {
		m.mu.Unlock()
		return
	}
	m.closing = true
	m.cancel()
	m.mu.Unlock()
	go func() {
		m.wg.Wait()
		m.mu.Lock()
		attempts := make([]*collectionReselectionAttempt, 0, len(m.attempts))
		for _, a := range m.attempts {
			attempts = append(attempts, a)
		}
		m.mu.Unlock()
		var err error
		for _, a := range attempts {
			a.mu.Lock()
			err = errors.Join(err, a.close())
			a.mu.Unlock()
		}
		rootErr := m.root.Close()
		err = errors.Join(err, rootErr)
		if rootErr == nil && m.cleanup != nil {
			err = errors.Join(err, m.cleanup(m.root))
		}
		m.mu.Lock()
		m.closeErr = err
		m.mu.Unlock()
		close(m.done)
	}()
}

func (m *CollectionReselectionManager) Wait(ctx context.Context) error {
	if ctx == nil {
		return ErrValidation
	}
	if m == nil || m.collectionReselectionManagerState == nil || m.mu == nil {
		return nil
	}
	select {
	case <-m.done:
		return m.Err()
	case <-ctx.Done():
		return ctx.Err()
	}
}

var reselectionManagerStopped = func() <-chan struct{} {
	done := make(chan struct{})
	close(done)
	return done
}()

// Done closes only after all owned work, the expiration loop, the spool root,
// and any runtime parent cleanup have joined. A shutdown wait deadline never
// releases those dependencies early. Nil and zero managers own no resources.
func (m *CollectionReselectionManager) Done() <-chan struct{} {
	if m == nil || m.collectionReselectionManagerState == nil || m.done == nil {
		return reselectionManagerStopped
	}
	return m.done
}

// Err returns the terminal ownership/cleanup error. An attempt's ordinary
// verification failure remains in that attempt's status, not this owner error.
func (m *CollectionReselectionManager) Err() error {
	if m == nil || m.collectionReselectionManagerState == nil || m.mu == nil {
		return nil
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.closeErr
}

func (m *CollectionReselectionManager) Ready() bool {
	if m == nil || m.collectionReselectionManagerState == nil || m.mu == nil {
		return false
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	return !m.closing && m.ctx.Err() == nil
}

func (a *collectionReselectionAttempt) close() error {
	if a == nil || a.collectionReselectionAttemptState == nil {
		return nil
	}
	if a.cancel != nil {
		a.cancel()
		a.cancel = nil
	}
	if a.proof != nil {
		a.proof.close()
		a.proof = nil
	}
	var err error
	if a.transfer != nil {
		err = a.transfer.Close()
		a.transfer = nil
	}
	if a.spool != nil {
		err = errors.Join(err, a.spool.Close())
		a.spool = nil
	}
	a.sources = nil
	return err
}

// CheckCreate checks the authenticated actor and original upload before an HTTP
// adapter reads a create body. It allocates no attempt, reservation or spool and
// does not renew the operation. Create repeats this observation after decoding.
func (m *CollectionReselectionManager) CheckCreate(ctx context.Context, id, actor string) error {
	if ctx == nil {
		return ErrValidation
	}
	if err := m.begin(); err != nil {
		return err
	}
	defer m.wg.Done()
	_, _, _, err := m.createPreflight(ctx, id, actor)
	return err
}

func (m *CollectionReselectionManager) createPreflight(ctx context.Context, id, actor string) (persistence.OperatorAuthority, *persistence.CollectionUploadView, persistence.CollectionState, error) {
	var empty persistence.OperatorAuthority
	var noHead persistence.CollectionState
	if err := m.catalog.readyContext(ctx); err != nil {
		return empty, nil, noHead, err
	}
	authority, err := m.catalog.store.ObserveOperatorAuthority(ctx, actor, m.now())
	if err != nil {
		return empty, nil, noHead, err
	}
	if _, err := m.catalog.store.CollectionOperationAs(ctx, id, actor, m.now()); err != nil {
		return empty, nil, noHead, err
	}
	view, head, err := m.catalog.store.CollectionUploadView(ctx, id, m.now())
	if err != nil {
		return empty, nil, noHead, err
	}
	if head.Actor != actor || head.Owner == nil || head.Owner.Actor != actor || head.Owner.Epoch != authority.Epoch {
		return empty, nil, noHead, ErrReselectionNotFound
	}
	if head.NormalizationProfile != collection.FileNormalizationProfile || head.ItemCount > 10_000 {
		return empty, nil, noHead, ErrReselectionConflict
	}
	current, err := m.catalog.store.ObserveOperatorAuthority(ctx, actor, m.now())
	if err != nil {
		return empty, nil, noHead, err
	}
	if current != authority {
		return empty, nil, noHead, persistence.ErrAuthenticationConflict
	}
	if err := view.Check(ctx, m.now()); err != nil {
		return empty, nil, noHead, err
	}
	if m.ctx.Err() != nil {
		return empty, nil, noHead, ErrUnavailable
	}
	return authority, view, head, nil
}

func (m *CollectionReselectionManager) Create(ctx context.Context, id, actor, profile string, count int) (CollectionReselectionStatus, error) {
	if ctx == nil || profile != collection.FileNormalizationProfile || count < 1 || count > 1000 {
		return CollectionReselectionStatus{}, ErrValidation
	}
	if err := m.begin(); err != nil {
		return CollectionReselectionStatus{}, err
	}
	defer m.wg.Done()
	authority, view, head, err := m.createPreflight(ctx, id, actor)
	if err != nil {
		return CollectionReselectionStatus{}, err
	}
	at := m.now()
	expiry := reselectionAttemptExpiry(at, head.ExpiresAt)
	a := &collectionReselectionAttempt{collectionReselectionAttemptState: &collectionReselectionAttemptState{mu: new(sync.Mutex), head: head, view: view, authority: authority, status: CollectionReselectionStatus{ID: uuid.NewString(), OperationID: id, NormalizationProfile: profile, Phase: "uploading", SourceCount: count, NextSource: 1, OperationUploaded: int64(head.Uploaded), ExpiresAt: expiry}}}
	m.mu.Lock()
	for key, last := range m.lastCreate {
		if !at.Before(last.Add(reselectionAttemptLifetime)) {
			delete(m.lastCreate, key)
		}
	}
	if m.closing || len(m.attempts) >= 4 || m.reserved > reselectionManagerBytes-reselectionAttemptBytes || len(m.lastCreate) >= 1024 || at.Before(m.lastCreate[id].Add(5*time.Second)) {
		m.mu.Unlock()
		return CollectionReselectionStatus{}, ErrReselectionBusy
	}
	for _, existing := range m.attempts {
		if existing.status.OperationID == id {
			m.mu.Unlock()
			return CollectionReselectionStatus{}, ErrReselectionBusy
		}
	}
	m.attempts[a.status.ID] = a
	m.reserved += reselectionAttemptBytes
	m.lastCreate[id] = at
	m.mu.Unlock()
	ok := false
	defer func() {
		if !ok {
			a.mu.Lock()
			_ = a.close()
			a.mu.Unlock()
			m.remove(a)
		}
	}()
	a.spool, err = newReselectionSpool(ctx, m.root, reselectionSpoolOptions{AttemptID: a.status.ID, MaxPlaintextBytes: 576 << 20, MaxEncodedBytes: reselectionAttemptBytes, MaxRecords: reselectionRecordLimit})
	if err != nil {
		return CollectionReselectionStatus{}, err
	}
	a.sources, err = newReselectionSources(a.spool, count, 64<<20)
	if err != nil {
		return CollectionReselectionStatus{}, err
	}
	if err := m.check(ctx, a, true); err != nil {
		return CollectionReselectionStatus{}, err
	}
	a.mu.Lock()
	a.ready = true
	result := a.status
	a.mu.Unlock()
	ok = true
	return result, nil
}

func reselectionAttemptExpiry(at, originalExpiry time.Time) time.Time {
	// Persisted expiry has no monotonic component. Re-anchor its remaining
	// duration at the local observation so wall-clock rollback cannot renew a
	// short attempt when now supplies a monotonic clock (time.Now).
	return at.Add(min(reselectionAttemptLifetime, originalExpiry.Sub(at)))
}

func (m *CollectionReselectionManager) remove(a *collectionReselectionAttempt) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.attempts[a.status.ID] == a {
		delete(m.attempts, a.status.ID)
		m.reserved -= reselectionAttemptBytes
	}
}

func (m *CollectionReselectionManager) lookup(ctx context.Context, id, attempt, actor string) (*collectionReselectionAttempt, error) {
	m.mu.Lock()
	a := m.attempts[attempt]
	m.mu.Unlock()
	if a == nil {
		return nil, ErrReselectionNotFound
	}
	if err := m.lockAttempt(ctx, a.mu); err != nil {
		return nil, err
	}
	if !a.ready || a.discarded || a.status.OperationID != id || a.authority.Actor != actor {
		a.mu.Unlock()
		return nil, ErrReselectionNotFound
	}
	return a, nil // caller owns a.mu, never the global map lock
}

// An upload owns this lock across cooperative filesystem I/O. Other HTTP calls
// must remain cancellable while waiting; owner cleanup still joins the writer.
func (m *CollectionReselectionManager) lockAttempt(ctx context.Context, mu *sync.Mutex) error {
	for {
		if err := ctx.Err(); err != nil {
			return err
		}
		if m.ctx.Err() != nil {
			return ErrUnavailable
		}
		if mu.TryLock() {
			if err := ctx.Err(); err != nil {
				mu.Unlock()
				return err
			}
			if m.ctx.Err() != nil {
				mu.Unlock()
				return ErrUnavailable
			}
			return nil
		}
		timer := time.NewTimer(time.Millisecond)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-m.ctx.Done():
			timer.Stop()
			return ErrUnavailable
		case <-timer.C:
		}
	}
}

func (m *CollectionReselectionManager) check(ctx context.Context, a *collectionReselectionAttempt, prefix bool) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if m.ctx.Err() != nil {
		return ErrUnavailable
	}
	if !m.now().Before(a.status.ExpiresAt) {
		return persistence.ErrOperationExpired
	}
	current, err := m.catalog.store.ObserveOperatorAuthority(ctx, a.authority.Actor, m.now())
	if err != nil {
		return err
	}
	if current != a.authority {
		return persistence.ErrAuthenticationConflict
	}
	if prefix {
		return a.view.Check(ctx, m.now())
	}
	_, err = m.catalog.store.CollectionOperationAs(ctx, a.head.ID, a.authority.Actor, m.now())
	return err
}

func (m *CollectionReselectionManager) Get(ctx context.Context, id, attempt, actor string) (CollectionReselectionStatus, error) {
	if ctx == nil {
		return CollectionReselectionStatus{}, ErrValidation
	}
	if err := m.begin(); err != nil {
		return CollectionReselectionStatus{}, err
	}
	defer m.wg.Done()
	a, err := m.lookup(ctx, id, attempt, actor)
	if err != nil {
		return CollectionReselectionStatus{}, err
	}
	defer a.mu.Unlock()
	if err := m.check(ctx, a, false); err != nil {
		return CollectionReselectionStatus{}, err
	}
	return a.status, nil
}

func (m *CollectionReselectionManager) Upload(ctx context.Context, id, attempt, actor string, source, offset uint64, end bool, body []byte) (CollectionReselectionStatus, error) {
	if ctx == nil || len(body) > reselectionFrameLimit {
		return CollectionReselectionStatus{}, ErrValidation
	}
	if err := m.begin(); err != nil {
		return CollectionReselectionStatus{}, err
	}
	defer m.wg.Done()
	a, err := m.lookup(ctx, id, attempt, actor)
	if err != nil {
		return CollectionReselectionStatus{}, err
	}
	defer a.mu.Unlock()
	if err := m.check(ctx, a, true); err != nil {
		return CollectionReselectionStatus{}, err
	}
	if a.status.Phase != "uploading" {
		return CollectionReselectionStatus{}, ErrReselectionConflict
	}
	if _, err := a.sources.append(ctx, source, offset, end, body); err != nil {
		return CollectionReselectionStatus{}, err
	}
	progress, err := a.sources.progress()
	if err != nil {
		return CollectionReselectionStatus{}, err
	}
	a.status.RawBytes = progress.RawBytes
	a.status.SourcesCompleted = progress.SourcesCompleted
	if progress.Complete {
		a.status.NextSource = 0
		a.status.NextOffset = 0
	} else {
		a.status.NextSource = progress.SourcesCompleted + 1
		if end {
			a.status.NextOffset = 0
		} else {
			a.status.NextOffset = int64(offset) + int64(len(body))
		}
	}
	if err := m.check(ctx, a, true); err != nil {
		return CollectionReselectionStatus{}, err
	}
	return a.status, nil
}

func (m *CollectionReselectionManager) Verify(ctx context.Context, id, attempt, actor string) (CollectionReselectionStatus, error) {
	return m.start(ctx, id, attempt, actor, false)
}
func (m *CollectionReselectionManager) Resume(ctx context.Context, id, attempt, actor string) (CollectionReselectionStatus, error) {
	return m.start(ctx, id, attempt, actor, true)
}

func (m *CollectionReselectionManager) start(ctx context.Context, id, attempt, actor string, transfer bool) (CollectionReselectionStatus, error) {
	if ctx == nil {
		return CollectionReselectionStatus{}, ErrValidation
	}
	if err := m.begin(); err != nil {
		return CollectionReselectionStatus{}, err
	}
	defer m.wg.Done()
	a, err := m.lookup(ctx, id, attempt, actor)
	if err != nil {
		return CollectionReselectionStatus{}, err
	}
	defer a.mu.Unlock()
	if err := m.check(ctx, a, !transfer); err != nil {
		return CollectionReselectionStatus{}, err
	}
	if !transfer && (a.status.Phase == "verifying" || a.status.Phase == "verified") || transfer && (a.status.Phase == "transferring" || a.status.Phase == "completed") {
		return a.status, nil
	}
	if !transfer && (a.status.Phase != "uploading" || a.status.SourcesCompleted != a.status.SourceCount) || transfer && a.status.Phase != "verified" && !(a.status.Phase == "failed" && a.transfer != nil) {
		return CollectionReselectionStatus{}, ErrReselectionConflict
	}
	started := time.Now()
	remaining := a.status.ExpiresAt.Sub(m.now())
	if remaining <= 0 {
		return CollectionReselectionStatus{}, persistence.ErrOperationExpired
	}
	// Map injected observation time to a real timer once. Sampling before the
	// admission lock ensures lock waits cannot extend the fixed deadline.
	deadline := started.Add(min(reselectionWorkTimeout, remaining))
	select {
	case m.workers <- struct{}{}:
	default:
		return CollectionReselectionStatus{}, ErrReselectionBusy
	}
	if err := m.begin(); err != nil {
		<-m.workers
		return CollectionReselectionStatus{}, err
	}
	work, cancel := context.WithDeadline(m.ctx, deadline)
	if err := work.Err(); err != nil {
		cancel()
		m.wg.Done()
		<-m.workers
		return CollectionReselectionStatus{}, err
	}
	a.cancel = cancel
	a.status.ErrorCode = ""
	if transfer {
		a.status.Phase = "transferring"
	} else {
		a.status.Phase = "verifying"
	}
	go m.work(work, a, transfer)
	return a.status, nil
}

func (m *CollectionReselectionManager) work(ctx context.Context, a *collectionReselectionAttempt, transfer bool) {
	defer m.wg.Done()
	defer func() { <-m.workers }()
	a.mu.Lock()
	sources, spool, originalProof, holder := a.sources, a.spool, a.proof, a.transfer
	a.mu.Unlock()
	var proof *collectionReselectionProof
	var err error
	if !transfer {
		proof, err = proveCollectionReselection(ctx, m.catalog, a.head.ID, a.authority.Actor, sources, spool, func(key persistence.CatalogKey) bool { return supportedKind(key.Kind) }, m.now)
		if err == nil {
			err = m.check(ctx, a, true)
		}
	} else {
		if holder == nil {
			holder, err = newReselectionTransfer(ctx, originalProof)
		}
		for err == nil {
			var progress reselectionTransferProgress
			progress, err = holder.step(ctx, func(commit func() error) error {
				if e := m.check(ctx, a, false); e != nil {
					return e
				}
				return commit()
			})
			if progress.Operation.Uploaded != nil {
				a.mu.Lock()
				a.status.OperationUploaded = *progress.Operation.Uploaded
				a.mu.Unlock()
			}
			if err != nil || progress.Complete {
				break
			}
		}
	}
	a.mu.Lock()
	defer a.mu.Unlock()
	if transfer && holder != nil {
		a.transfer, a.proof = holder, nil
	}
	if a.cancel != nil {
		a.cancel()
		a.cancel = nil
	}
	if a.discarded {
		if proof != nil {
			proof.close()
		}
		_ = a.close()
		m.remove(a)
		return
	}
	if err != nil {
		if proof != nil {
			proof.close()
		}
		a.status.Phase = "failed"
		a.status.ErrorCode = reselectionFailureCode(err, transfer)
		return
	}
	if transfer {
		a.status.Phase = "completed"
	} else {
		a.proof = proof
		a.status.Phase = "verified"
	}
}

func reselectionFailureCode(err error, transfer bool) string {
	switch {
	case errors.Is(err, errReselectionInput):
		return "input_mismatch"
	case errors.Is(err, persistence.ErrOperatorAuthorityDenied), errors.Is(err, persistence.ErrAuthenticationConflict), errors.Is(err, errCollectionReadDenied):
		return "authorization_changed"
	case errors.Is(err, persistence.ErrOperationExpired):
		return "expired"
	case errors.Is(err, persistence.ErrCollectionConflict):
		return "operation_changed"
	case errors.Is(err, errReselectionSpoolQuota), errors.Is(err, persistence.ErrCollectionQuota):
		return "quota_exceeded"
	case errors.Is(err, ErrUnavailable), errors.Is(err, errReselectionSpool), errors.Is(err, persistence.ErrCollectionUnavailable):
		return "storage_unavailable"
	case transfer:
		return "transfer_failed"
	default:
		return "verification_failed"
	}
}

func (m *CollectionReselectionManager) Discard(ctx context.Context, id, attempt, actor string) error {
	if ctx == nil {
		return ErrValidation
	}
	if err := m.begin(); err != nil {
		return err
	}
	defer m.wg.Done()
	a, err := m.lookup(ctx, id, attempt, actor)
	if err != nil {
		return err
	}
	defer a.mu.Unlock()
	if err := m.check(ctx, a, false); err != nil {
		return err
	}
	a.discarded = true
	if a.cancel != nil {
		a.cancel()
		return nil
	}
	err = a.close()
	m.remove(a)
	return err
}

func (m *CollectionReselectionManager) expireLoop() {
	defer m.wg.Done()
	tick := time.NewTicker(time.Second)
	defer tick.Stop()
	for {
		select {
		case <-m.ctx.Done():
			m.BeginStop()
			return
		case <-tick.C:
			m.expire()
		}
	}
}
func (m *CollectionReselectionManager) expire() {
	if m.begin() != nil {
		return
	}
	defer m.wg.Done()
	m.mu.Lock()
	list := make([]*collectionReselectionAttempt, 0, len(m.attempts))
	for _, a := range m.attempts {
		list = append(list, a)
	}
	m.mu.Unlock()
	for _, a := range list {
		a.mu.Lock()
		if a.ready && !m.now().Before(a.status.ExpiresAt) {
			a.discarded = true
			if a.cancel != nil {
				a.cancel()
			} else {
				_ = a.close()
				m.remove(a)
			}
		}
		a.mu.Unlock()
	}
}
