//go:build externaljobs

package persistence

import (
	"context"
	"encoding/json"
	"errors"
	"math"
	"reflect"
	"slices"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/hashicorp/raft"
)

// WorkerSessionFormatVersion adds session ownership and empty poll receipts.
// It grants no assignment, start permission, or external execution.
const WorkerSessionFormatVersion = 19
const workerSessionSnapshotMagic = "CPRA-COLLECTION-SNAPSHOT-19\n"
const WorkerSessionLifetime = 2 * time.Minute
const (
	MaxWorkerSessions            = 1024
	MaxWorkerSessionCapabilities = 64
	MaxWorkerSessionBytes        = 16 << 20
)

var (
	ErrWorkerSessionInvalid     = errors.New("invalid worker session request")
	ErrWorkerSessionConflict    = errors.New("worker session conflicts with retained ownership or input")
	ErrWorkerSessionExpired     = errors.New("worker session expired")
	ErrWorkerSessionSequence    = errors.New("worker poll sequence conflicts with retained progress")
	ErrWorkerSessionIdentity    = errors.New("worker protocol server identity mismatch")
	ErrWorkerSessionQuota       = errors.New("worker session capacity exhausted")
	ErrWorkerSessionUnavailable = errors.New("worker session state unavailable")
)

type WorkerServerIdentity struct{ ServerID, OwnerEpoch string }
type WorkerSessionCapability struct {
	JobTypeID string `json:"job_type_id"`
	Version   string `json:"version"`
	Category  string `json:"category"`
}
type WorkerPollRequest struct {
	ServerID        string                    `json:"server_id"`
	WorkerID        string                    `json:"worker_id"`
	ClientSessionID string                    `json:"client_session_id"`
	SessionID       string                    `json:"session_id"`
	PollSequence    uint64                    `json:"poll_sequence"`
	Capabilities    []WorkerSessionCapability `json:"capabilities"`
	Capacity        int                       `json:"capacity"`
	Limit           int                       `json:"limit"`
	WaitSeconds     int                       `json:"wait_seconds"`
}
type WorkerPollResponse struct {
	ServerID         string        `json:"server_id"`
	WorkerUID        string        `json:"worker_uid"`
	ClientSessionID  string        `json:"client_session_id"`
	SessionID        string        `json:"session_id"`
	PollSequence     uint64        `json:"poll_sequence"`
	SessionExpiresAt time.Time     `json:"session_expires_at"`
	Offers           []WorkerOffer `json:"offers,omitempty"`
}

// WorkerSessionCommand is generated by CommitWorkerPoll, not HTTP input.
// All time and randomness are fixed before admission; Apply performs no I/O.
type WorkerSessionCommand struct {
	NodeID            string            `json:"node_id"`
	OwnerEpoch        string            `json:"owner_epoch"`
	Authority         WorkerAuthority   `json:"authority"`
	Request           WorkerPollRequest `json:"request"`
	ProposedSessionID string            `json:"proposed_session_id"`
	ProposedLeaseIDs  []string          `json:"proposed_lease_ids,omitempty"`
}
type workerSessionRecord struct {
	WorkerID      string             `json:"worker_id"`
	WorkerUID     string             `json:"worker_uid"`
	OwnerEpoch    string             `json:"owner_epoch"`
	OpenedAt      time.Time          `json:"opened_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	Request       WorkerPollRequest  `json:"request"`
	RequestDigest string             `json:"request_digest"`
	Response      WorkerPollResponse `json:"response"`
}
type workerSessionImage struct {
	Version      int                            `json:"version"`
	NodeID       string                         `json:"node_id"`
	PolicyEpoch  string                         `json:"policy_epoch"`
	Sessions     map[string]workerSessionRecord `json:"sessions"`
	EncodedBytes int64                          `json:"encoded_bytes"`
}

func (r WorkerPollRequest) clone() WorkerPollRequest {
	r.Capabilities = slices.Clone(r.Capabilities)
	return r
}
func (r workerSessionRecord) clone() workerSessionRecord {
	r.Request = r.Request.clone()
	r.Response = r.Response.clone()
	return r
}
func (i *workerSessionImage) clone() *workerSessionImage {
	if i == nil {
		return nil
	}
	out := *i
	out.Sessions = make(map[string]workerSessionRecord, len(i.Sessions))
	for k, v := range i.Sessions {
		out.Sessions[k] = v.clone()
	}
	return &out
}

func workerProtocolServerID(nodeID, epoch string) string {
	return "cpra-worker-v1:" + identity("cpra/worker/server/v1\x00"+nodeID+"\x00"+epoch)
}
func workerCapabilityKey(c WorkerSessionCapability) string {
	return c.JobTypeID + "\x00" + c.Version + "\x00" + c.Category
}
func validWorkerCapability(c WorkerSessionCapability) bool {
	return catalogIdentifier(c.JobTypeID, 256) && jobTypeSelector(c.Version) && (c.Category == "check" || c.Category == "recovery" || c.Category == "notification")
}
func (r WorkerPollRequest) validate() error {
	if !catalogIdentifier(r.ServerID, 256) || !validAuthenticationID(r.WorkerID) || !catalogIdentifier(r.ClientSessionID, 256) || r.SessionID != "" && !catalogIdentifier(r.SessionID, 256) || r.PollSequence == 0 || r.PollSequence > math.MaxInt64 || r.SessionID == "" && r.PollSequence != 1 || r.Capacity < 1 || r.Capacity > 100 || r.Limit < 1 || r.Limit > 100 || r.Limit > r.Capacity || r.WaitSeconds < 0 || r.WaitSeconds > 25 || len(r.Capabilities) < 1 || len(r.Capabilities) > MaxWorkerSessionCapabilities {
		return ErrWorkerSessionInvalid
	}
	previous := ""
	for _, c := range r.Capabilities {
		if !validWorkerCapability(c) {
			return ErrWorkerSessionInvalid
		}
		key := workerCapabilityKey(c)
		if key <= previous {
			return ErrWorkerSessionInvalid
		}
		previous = key
	}
	return nil
}
func normalizeWorkerPoll(r WorkerPollRequest) (WorkerPollRequest, error) {
	if len(r.Capabilities) > MaxWorkerSessionCapabilities {
		return WorkerPollRequest{}, ErrWorkerSessionInvalid
	}
	for _, c := range r.Capabilities {
		if !validWorkerCapability(c) {
			return WorkerPollRequest{}, ErrWorkerSessionInvalid
		}
	}
	r = r.clone()
	slices.SortFunc(r.Capabilities, func(a, b WorkerSessionCapability) int {
		return strings.Compare(workerCapabilityKey(a), workerCapabilityKey(b))
	})
	return r, r.validate()
}
func (a WorkerAuthority) sessionShapeValid() bool {
	return validAuthenticationID(a.Epoch) && validAuthenticationID(a.PolicyRevision) && validAuthenticationID(a.WorkerID) && validAuthenticationID(a.WorkerUID) && validAuthenticationID(a.CredentialRevision) && validAuthenticationID(a.GrantRevision)
}
func (c WorkerSessionCommand) validate(at time.Time) error {
	if len(c.ProposedLeaseIDs) > 0 {
		if len(c.ProposedLeaseIDs) != c.Request.Limit {
			return ErrWorkerSessionInvalid
		}
		seen := map[string]bool{}
		for _, id := range c.ProposedLeaseIDs {
			if !catalogIdentifier(id, 256) || seen[id] {
				return ErrWorkerSessionInvalid
			}
			seen[id] = true
		}
	}
	if !catalogIdentifier(c.NodeID, 256) || !catalogIdentifier(c.OwnerEpoch, 256) || !catalogIdentifier(c.ProposedSessionID, 256) || !c.Authority.sessionShapeValid() || c.Authority.WorkerID != c.Request.WorkerID || c.Request.validate() != nil || at.IsZero() || at.Year() < 1 || at.Year() > 9998 || c.Request.ServerID != workerProtocolServerID(c.NodeID, c.Authority.Epoch) {
		return ErrWorkerSessionInvalid
	}
	return nil
}

// This projection is frozen independently of future poll/session fields.
type workerPollDigestV1 struct {
	ServerID        string                    `json:"server_id"`
	WorkerID        string                    `json:"worker_id"`
	ClientSessionID string                    `json:"client_session_id"`
	SessionID       string                    `json:"session_id"`
	PollSequence    uint64                    `json:"poll_sequence"`
	Capabilities    []WorkerSessionCapability `json:"capabilities"`
	Capacity        int                       `json:"capacity"`
	Limit           int                       `json:"limit"`
	WaitSeconds     int                       `json:"wait_seconds"`
}

func workerPollDigest(r WorkerPollRequest) string {
	v := workerPollDigestV1{r.ServerID, r.WorkerID, r.ClientSessionID, r.SessionID, r.PollSequence, r.Capabilities, r.Capacity, r.Limit, r.WaitSeconds}
	raw, _ := json.Marshal(v)
	return identity("cpra/worker/poll/v1\x00" + string(raw))
}

func (f *machine) checkWorkerPollAuthority(a WorkerAuthority, request WorkerPollRequest, at time.Time) error {
	if err := f.workerPolicyReady(at); err != nil {
		return err
	}
	w, ok := f.image.WorkerPolicy.Workers[a.WorkerID]
	if !ok || !workerCredentialEligible(w, at) || a != workerAuthority(f.image.WorkerPolicy, w) || request.WorkerID != w.ID {
		return ErrWorkerAuthorityDenied
	}
	for _, capability := range request.Capabilities {
		matched := false
		for _, grant := range w.Grants {
			if capability.JobTypeID == grant.JobTypeID && capability.Version == grant.Version && capability.Category == grant.Category && validateWorkerGrantReference(f.image, w, grant) == nil {
				matched = true
				break
			}
		}
		if !matched {
			return ErrWorkerAuthorityDenied
		}
	}
	return nil
}

func workerSessionError(err error) error {
	if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) || errors.Is(err, ErrWorkerAuthorityDenied) || errors.Is(err, ErrWorkerPolicyUnavailable) || errors.Is(err, ErrWorkerSessionIdentity) || errors.Is(err, ErrWorkerSessionExpired) {
		return err
	}
	return ErrWorkerSessionUnavailable
}

// WorkerProtocolIdentity permits stopped identity inspection; an administrator
// has no running owner epoch and cannot commit a poll.
func (s *Store) WorkerProtocolIdentity(ctx context.Context) (WorkerServerIdentity, error) {
	var out WorkerServerIdentity
	err := s.withAuthenticationRead(ctx, func(f *machine) error {
		if f.image.WorkerPolicy == nil || !validAuthenticationID(f.image.WorkerPolicy.Epoch) {
			return ErrWorkerPolicyUnavailable
		}
		if !s.administrative {
			if err := f.workerPolicyReady(time.Now().UTC()); err != nil {
				return err
			}
		}
		if sessions := f.image.WorkerSessions; sessions != nil && sessions.NodeID != s.nodeID {
			return ErrWorkerSessionIdentity
		}
		out.ServerID = workerProtocolServerID(s.nodeID, f.image.WorkerPolicy.Epoch)
		if !s.administrative {
			if s.executorSession != f.image.LocalExecutorSession || s.raft != nil && s.raft.State() != raft.Leader {
				return ErrWorkerSessionUnavailable
			}
			out.OwnerEpoch = s.executorSession
		}
		return nil
	})
	if err != nil {
		return WorkerServerIdentity{}, workerSessionError(err)
	}
	return out, nil
}

// CommitWorkerPoll commits or reconciles one bounded assignment response. An uncertain
// submit is returned to the caller; only an explicit identical poll may retry.
func (s *Store) CommitWorkerPoll(ctx context.Context, authority WorkerAuthority, request WorkerPollRequest) (WorkerPollResponse, error) {
	if ctx == nil {
		return WorkerPollResponse{}, ErrWorkerSessionInvalid
	}
	if err := ctx.Err(); err != nil {
		return WorkerPollResponse{}, err
	}
	if s.administrative {
		return WorkerPollResponse{}, ErrWorkerSessionUnavailable
	}
	request, err := normalizeWorkerPoll(request)
	if err != nil {
		return WorkerPollResponse{}, err
	}
	c := WorkerSessionCommand{NodeID: s.nodeID, OwnerEpoch: s.executorSession, Authority: authority, Request: request, ProposedSessionID: uuid.NewString()}
	c.ProposedLeaseIDs = make([]string, request.Limit)
	for n := range c.ProposedLeaseIDs {
		c.ProposedLeaseIDs[n] = uuid.NewString()
	}
	at := time.Now().UTC()
	if request.ServerID != workerProtocolServerID(s.nodeID, authority.Epoch) {
		return WorkerPollResponse{}, ErrWorkerSessionIdentity
	}
	if err = c.validate(at); err != nil {
		return WorkerPollResponse{}, err
	}
	results, err := s.Submit(ctx, []Command{{Kind: "worker_poll", At: at, commandExtensions: commandExtensions{WorkerSession: &c}}})
	if err != nil {
		return WorkerPollResponse{}, errors.Join(ErrCommitUnconfirmed, workerSessionError(err))
	}
	if len(results) != 1 {
		return WorkerPollResponse{}, errors.Join(ErrCommitUnconfirmed, ErrWorkerSessionUnavailable)
	}
	if results[0].Err != nil {
		return WorkerPollResponse{}, results[0].Err
	}
	if !results[0].Allowed || results[0].WorkerPoll == nil {
		return WorkerPollResponse{}, errors.Join(ErrCommitUnconfirmed, ErrWorkerSessionUnavailable)
	}
	response := results[0].WorkerPoll.clone()
	// A delayed commit/reply must not expose an already expired response or an
	// observation whose credential/grant authority changed while it was queued.
	err = s.withAuthenticationRead(ctx, func(f *machine) error {
		now := time.Now().UTC()
		if err := f.checkWorkerPollAuthority(authority, request, now); err != nil {
			return err
		}
		if f.image.LocalExecutorSession != c.OwnerEpoch || !time.Now().Before(response.SessionExpiresAt) {
			return ErrWorkerSessionExpired
		}
		if !workerCredentialEligible(f.image.WorkerPolicy.Workers[authority.WorkerID], time.Now().UTC()) {
			return ErrWorkerAuthorityDenied
		}
		if s.raft != nil && s.raft.State() != raft.Leader {
			return ErrWorkerSessionUnavailable
		}
		return nil
	})
	if err != nil {
		return WorkerPollResponse{}, workerSessionError(err)
	}
	return response, nil
}

func sameWorkerCapabilities(a, b []WorkerSessionCapability) bool { return reflect.DeepEqual(a, b) }
