apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpra-service-discovery
  namespace: payments
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cpra-service-discovery
  namespace: payments
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cpra-service-discovery
  namespace: payments
subjects:
  - kind: ServiceAccount
    name: cpra-service-discovery
    namespace: payments
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cpra-service-discovery
