#!/usr/bin/env python3
"""Generate the browser's base wire models and form descriptors without dependencies.

This repository-owned generator supports the constructs in CPRa's canonical model
input. It emits wire types, not a runtime JSON Schema validator. Constraints such
as minimum lengths, uniqueItems and `not` remain enforced by the server; UI forms
add user-facing checks. Unknown type constructs fail instead of becoming `any`.
No externaljobs overlay is read or included. The source hash pins the generator.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
CONFIG = ROOT / "dashboard/api-generation.json"


def quote(value):
    return json.dumps(value, ensure_ascii=True)


def wire_type(schema, names):
    if schema is True:
        return "unknown"
    if schema is False:
        return "never"
    if not isinstance(schema, dict):
        raise ValueError("Expected a JSON Schema object")
    if "$ref" in schema:
        prefix = "#/components/schemas/"
        reference = schema["$ref"]
        if not reference.startswith(prefix) or reference[len(prefix):] not in names:
            raise ValueError("Unsupported schema reference: " + reference)
        return reference[len(prefix):]
    for key, joiner in (("oneOf", " | "), ("anyOf", " | "), ("allOf", " & ")):
        if key in schema:
            return "(" + joiner.join(wire_type(child, names) for child in schema[key]) + ")"
    if "const" in schema:
        return quote(schema["const"])
    if "enum" in schema:
        return " | ".join(quote(value) for value in schema["enum"])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(wire_type({**schema, "type": item}, names) for item in kind)
    if kind in ("string", "boolean", "null"):
        return kind
    if kind in ("integer", "number"):
        return "number"
    if kind == "array":
        return "Array<" + wire_type(schema.get("items", {}), names) + ">"
    if kind == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        fields = []
        for key, child in properties.items():
            if child.get("writeOnly"):
                fields.append("  /** Write-only input. Never populate from a read response. */")
            fields.append("  " + quote(key) + ("" if key in required else "?") + ": " + wire_type(child, names) + ";")
        extra = schema.get("additionalProperties", True)
        if extra is not False:
            fields.append("  [key: string]: " + (wire_type(extra, names) if isinstance(extra, dict) else "unknown") + ";")
        return "{\n" + "\n".join(fields) + "\n}"
    if kind is not None:
        raise ValueError("Unsupported schema type: " + str(kind))
    # Deliberately untyped JSON and json.RawMessage are wire-level unknowns.
    return "unknown"


def generate():
    config = json.loads(CONFIG.read_text())
    if config["format"] != 1:
        raise ValueError("Unsupported browser generation format")
    schema_path = ROOT / config["models"]
    operation_path = ROOT / config["operations"]
    contract_path = ROOT / config["contract"]
    contract = json.loads(contract_path.read_text())
    schemas = json.loads(schema_path.read_text())["components"]["schemas"]
    names = set(schemas)
    if any(not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name) for name in names):
        raise ValueError("Unsupported TypeScript schema name")
    inputs = [CONFIG, schema_path, operation_path, contract_path, Path(__file__).resolve()]
    lines = ["// Generated by scripts/dashboard/generate_api.py. Do not edit.",
             "// Wire types preserve presence; validation constraints remain server-authoritative."]
    for path in inputs:
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        lines.append("// sha256 " + str(path.relative_to(ROOT)) + " " + digest)
    for name, schema in schemas.items():
        lines.append("\nexport type " + name + " = " + wire_type(schema, names) + ";")
    operations = {}
    for item in json.loads(operation_path.read_text()):
        if item["buildTag"]:
            continue
        operation = contract["paths"][item["path"]][item["method"].lower()]
        if operation["operationId"] != item["operationID"]:
            raise ValueError("Operation inventory does not match its HTTP contract")
        create_only = any(parameter.get("in") == "header" and parameter.get("name") == "If-None-Match" and
                          parameter.get("required") and parameter.get("schema", {}).get("enum") == ["*"]
                          for parameter in operation.get("parameters", []))
        operations[item["operationID"]] = {"method": item["method"], "path": item["path"], "cas": item["cas"], "createOnly": create_only}
    lines.append("\nexport const operationContracts = " + json.dumps(operations, indent=2, sort_keys=True) + " as const;")
    for category in ("notification", "check", "recovery"):
        descriptors = {}
        for driver, spec in config[category + "Drivers"].items():
            props = schemas[spec["schema"]]["properties"]
            if set(spec["protected"]) - props.keys():
                raise ValueError("Protected field absent from " + driver + " schema")
            if set(spec.get("labels", {})) - props.keys():
                raise ValueError("Label field absent from " + driver + " schema")
            fields = []
            for key, shape in props.items():
                if "$ref" in shape:
                    if shape["$ref"] != "#/components/schemas/Duration":
                        raise ValueError("Unsupported driver field reference")
                    kind = "duration"
                else:
                    kind = shape["type"]
                if kind == "array":
                    item_type = shape["items"].get("type")
                    if item_type not in ("string", "integer", "number"):
                        raise ValueError("Unsupported driver array field")
                    kind = "string-list" if item_type == "string" else "number-list"
                elif kind == "object":
                    if shape.get("additionalProperties") != {"type": "string"}:
                        raise ValueError("Unsupported driver object field")
                    kind = "string-map"
                elif kind in ("integer", "number"):
                    kind = "number"
                label = spec.get("labels", {}).get(key, re.sub(r"([a-z])([A-Z])", r"\1 \2", key).capitalize())
                fields.append({"key": key, "label": label, "type": kind, "protected": key in spec["protected"]})
            descriptors[driver] = fields
        lines.append("\nexport const " + category + "Fields = " + json.dumps(descriptors, indent=2) + " as const;")
    # The browser uses only this bounded structural projection to prevent an
    # unknown resource field from being silently discarded during replacement.
    shapes = {name: schemas[name] for name in config["monitorShapes"]}
    lines.append("\nexport const monitorShapes = " + json.dumps(shapes, indent=2, sort_keys=True) + " as const;")
    return ROOT / config["output"], "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed output differs; do not write")
    args = parser.parse_args()
    output, content = generate()
    if args.check:
        if not output.exists() or output.read_text() != content:
            parser.error("Browser API models are stale; regenerate and review the diff")
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content)


if __name__ == "__main__":
    main()
