package collection

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"reflect"
	"strings"
	"testing"
	"testing/iotest"

	"github.com/ziad-hsn/cpra/sdk/go/api"
)

// This file is a fixed conformance oracle shared with the Wasm qualification
// harness. Expected JSON is reviewed literal data, never output regenerated by
// the production decoder during a test. A semantic change needs a new profile.
func TestNormalizeFileFixedProfileFixtures(t *testing.T) {
	raw, err := os.ReadFile("testdata/file-base-v1.json")
	if err != nil {
		t.Fatal(err)
	}
	type row struct {
		ID       string `json:"id"`
		Document int    `json:"document"`
		Item     int    `json:"item"`
		JSON     string `json:"json"`
	}
	var fixtures struct {
		Profile string `json:"profile"`
		Cases   []struct {
			Name         string `json:"name"`
			Source       string `json:"source"`
			SourceBase64 string `json:"sourceBase64"`
			Valid        bool   `json:"valid"`
			Items        []row  `json:"items"`
		} `json:"cases"`
	}
	if err := json.Unmarshal(raw, &fixtures); err != nil || fixtures.Profile != FileNormalizationProfile || len(fixtures.Cases) < 30 {
		t.Fatal("invalid normalization contract fixtures", err)
	}
	for _, fixture := range fixtures.Cases {
		t.Run(fixture.Name, func(t *testing.T) {
			source := []byte(fixture.Source)
			if fixture.SourceBase64 != "" {
				var err error
				source, err = base64.StdEncoding.DecodeString(fixture.SourceBase64)
				if err != nil {
					t.Fatal(err)
				}
			}
			for _, chunked := range []bool{false, true} {
				var reader io.Reader = bytes.NewReader(source)
				if chunked {
					reader = iotest.OneByteReader(reader)
				}
				got := []row{}
				err := NormalizeFile(context.Background(), reader, fixtures.Profile, DecodeOptions{SourceName: "source"}, func(item NormalizedItem) error {
					if item.Location.Source != "source" {
						t.Fatal("source attribution changed")
					}
					got = append(got, row{item.ID, item.Location.Document, item.Location.Item, string(item.JSON)})
					return nil
				})
				if (err == nil) != fixture.Valid || !reflect.DeepEqual(got, fixture.Items) {
					t.Fatalf("profile conformance changed (chunked=%t): valid=%t error=%v\nrows=%#v\nwant=%#v", chunked, err == nil, err, got, fixture.Items)
				}
			}
		})
	}
}

func TestNormalizeFileUTF8Stream(t *testing.T) {
	for _, input := range [][]byte{
		[]byte("plain"), []byte("é猫😀"), []byte("\ufffd"), []byte(strings.Repeat("a", (32<<10)-2) + "😀猫"),
		{0xff}, {0xc0, 0x80}, {0xe2, 0x82}, {0xf4, 0x90, 0x80, 0x80}, {0xed, 0xa0, 0x80},
	} {
		valid := bytes.Equal(bytes.ToValidUTF8(input, []byte("?")), input)
		for _, chunked := range []bool{false, true} {
			var source io.Reader = bytes.NewReader(input)
			if chunked {
				source = iotest.OneByteReader(source)
			}
			got, err := io.ReadAll(&fileUTF8Reader{r: source})
			if valid && (err != nil || !bytes.Equal(input, got)) {
				t.Fatal("valid UTF-8 changed", err)
			}
			if !valid && !errors.Is(err, errFileUTF8) {
				t.Fatal("invalid UTF-8 accepted", err)
			}
		}
	}
	readerFailure := errors.New("source failed")
	_, err := io.ReadAll(&fileUTF8Reader{r: iotest.ErrReader(readerFailure)})
	if !errors.Is(err, readerFailure) {
		t.Fatal("source error was lost", err)
	}
}

const normalizedRecipient = `{"apiVersion":"cpra.io/v2","kind":"Recipient","metadata":{"id":"alice"},"spec":{"endpointRefs":["mail"]}}`

func TestNormalizeFileProfileAndBounds(t *testing.T) {
	for _, profile := range []string{"", "cpra.file.base.v0", "cpra.file.external.v1"} {
		if err := NormalizeFile(context.Background(), strings.NewReader(normalizedRecipient), profile, DecodeOptions{}, func(NormalizedItem) error { t.Fatal("unknown profile invoked callback"); return nil }); !errors.Is(err, ErrUnsupportedNormalization) {
			t.Fatal("unknown profile was not distinct", err)
		}
	}
	for _, options := range []DecodeOptions{
		{MaxBytes: (64 << 20) + 1}, {MaxResourceBytes: (1 << 20) + 1}, {MaxDocumentBytes: (16 << 20) + 1}, {MaxResources: 10_001},
		{MaxBytes: -1}, {MaxResourceBytes: -1}, {MaxDocumentBytes: -1}, {MaxResources: -1},
	} {
		if err := NormalizeFile(context.Background(), strings.NewReader(normalizedRecipient), FileNormalizationProfile, options, func(NormalizedItem) error { t.Fatal("invalid limit invoked callback"); return nil }); err == nil {
			t.Fatal("profile limits expanded")
		}
	}
	for _, limit := range []int64{int64(len(normalizedRecipient)) - 1, int64(len(normalizedRecipient))} {
		err := NormalizeFile(context.Background(), strings.NewReader(normalizedRecipient), FileNormalizationProfile, DecodeOptions{MaxBytes: limit}, func(NormalizedItem) error { return nil })
		if (err == nil) != (limit == int64(len(normalizedRecipient))) {
			t.Fatal("source byte boundary changed", err)
		}
	}
	for _, limit := range []int{len(normalizedRecipient) - 1, len(normalizedRecipient)} {
		err := NormalizeFile(context.Background(), strings.NewReader(normalizedRecipient), FileNormalizationProfile, DecodeOptions{MaxResourceBytes: limit}, func(NormalizedItem) error { return nil })
		if (err == nil) != (limit == len(normalizedRecipient)) {
			t.Fatal("resource byte boundary changed", err)
		}
	}
	second := strings.Replace(normalizedRecipient, "alice", "bob", 1)
	visits := 0
	err := NormalizeFile(context.Background(), strings.NewReader(normalizedRecipient+"\n"+second), FileNormalizationProfile, DecodeOptions{MaxResources: 1}, func(NormalizedItem) error { visits++; return nil })
	if err == nil || visits != 1 {
		t.Fatal("resource-count bound changed", err, visits)
	}
}

func TestNormalizeFileDocumentBoundsAndStreaming(t *testing.T) {
	// This exact raw YAML metadata document is 128 bytes, including newlines.
	base := "apiVersion: cpra.io/v2\nkind: Recipient\nmetadata: {id: alice}\nspec: {endpointRefs: [mail]}\n"
	input := base + "#" + strings.Repeat("x", 128-len(base)-2) + "\n"
	for _, limit := range []int{127, 128} {
		err := NormalizeFile(context.Background(), strings.NewReader(input), FileNormalizationProfile, DecodeOptions{MaxResourceBytes: 105, MaxDocumentBytes: limit}, func(NormalizedItem) error { return nil })
		if (err == nil) != (limit == 128) {
			t.Fatal("YAML document metadata limit changed", err)
		}
	}
	// Arrays have a per-resource limit rather than retaining a whole document.
	many := "[" + normalizedRecipient + "," + strings.Replace(normalizedRecipient, "alice", "bob", 1) + "]"
	err := NormalizeFile(context.Background(), strings.NewReader(many), FileNormalizationProfile, DecodeOptions{MaxResourceBytes: 105, MaxDocumentBytes: 105}, func(NormalizedItem) error { return nil })
	if err != nil {
		t.Fatal("streamed array was treated as one metadata document", err)
	}
	// JSON document metadata counts individual non-list value bytes.
	for _, limit := range []int{29, 30} {
		source := `{"version":"` + strings.Repeat("x", 28) + `","monitors":[]}`
		err := NormalizeFile(context.Background(), strings.NewReader(source), FileNormalizationProfile, DecodeOptions{MaxResourceBytes: 1, MaxDocumentBytes: limit}, func(NormalizedItem) error { return nil })
		if (err == nil) != (limit == 30) {
			t.Fatal("JSON document metadata limit changed", err)
		}
	}
}

func TestNormalizeFileDefaultDocumentAndResourceCeilings(t *testing.T) {
	// Comments count as document metadata. Fixed-size lines avoid conflating
	// the independent source-line bound with the 16 MiB document ceiling.
	comments := strings.Repeat("#"+strings.Repeat("x", 62)+"\n", (16<<20)/64)
	for _, extra := range []string{"", "#\n"} {
		err := NormalizeFile(context.Background(), io.MultiReader(strings.NewReader(comments), strings.NewReader(extra)), FileNormalizationProfile, DecodeOptions{}, func(NormalizedItem) error { t.Fatal("comments emitted a resource"); return nil })
		if (err == nil) != (extra == "") {
			t.Fatal("default document ceiling changed", err)
		}
	}
	prefix := `{"apiVersion":"cpra.io/v2","kind":"Credential","metadata":{"id":"large"},"spec":{"value":"`
	suffix := `"}}`
	for _, total := range []int{1 << 20, (1 << 20) + 1} {
		source := prefix + strings.Repeat("x", total-len(prefix)-len(suffix)) + suffix
		visits := 0
		err := NormalizeFile(context.Background(), strings.NewReader(source), FileNormalizationProfile, DecodeOptions{}, func(item NormalizedItem) error {
			visits++
			if len(item.JSON) != total {
				t.Fatal("resource bytes changed")
			}
			return nil
		})
		wantVisits := 0
		if total == 1<<20 {
			wantVisits = 1
		}
		if (err == nil) != (total == 1<<20) || visits != wantVisits {
			t.Fatal("default resource ceiling changed", err, visits)
		}
	}
}

func TestNormalizeFileBoundsEscapedJSONBeforeCallback(t *testing.T) {
	prefix := `{"apiVersion":"cpra.io/v2","kind":"Credential","metadata":{"id":"escaped"},"spec":{"value":"`
	suffix := `"}}`
	value := strings.Repeat("<>&", 30)
	want := prefix + strings.Repeat(`\u003c\u003e\u0026`, 30) + suffix
	for _, source := range []string{
		prefix + value + suffix,
		"apiVersion: cpra.io/v2\nkind: Credential\nmetadata: {id: escaped}\nspec:\n  value: \"" + value + "\"\n",
	} {
		if len(source) >= len(want)-1 {
			t.Fatal("fixture does not expand")
		}
		for _, limit := range []int{len(want) - 1, len(want)} {
			visits := 0
			err := NormalizeFile(context.Background(), strings.NewReader(source), FileNormalizationProfile, DecodeOptions{MaxResourceBytes: limit}, func(item NormalizedItem) error {
				visits++
				if string(item.JSON) != want {
					t.Fatal("HTML escaping changed")
				}
				return nil
			})
			if limit < len(want) && (err == nil || visits != 0) {
				t.Fatal("escaped resource exceeded its bound before callback", err, visits)
			}
			if limit == len(want) && (err != nil || visits != 1) {
				t.Fatal("exact escaped boundary rejected", err, visits)
			}
		}
	}
}

func TestNormalizeFileCancellationCallbacksAndPrivateValues(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	err := NormalizeFile(ctx, strings.NewReader(normalizedRecipient), FileNormalizationProfile, DecodeOptions{}, func(NormalizedItem) error { t.Fatal("canceled callback ran"); return nil })
	if !errors.Is(err, context.Canceled) {
		t.Fatal(err)
	}
	sink := errors.New("staging full")
	err = NormalizeFile(context.Background(), strings.NewReader(normalizedRecipient), FileNormalizationProfile, DecodeOptions{}, func(NormalizedItem) error { return sink })
	if !errors.Is(err, sink) {
		t.Fatal("staging error lost", err)
	}
	item := NormalizedItem{ID: "Credential/private-name", Location: Location{Source: "private-path"}, JSON: []byte("PRIVATE-CANARY")}
	for _, format := range []string{"%v", "%+v", "%#v"} {
		if strings.Contains(fmt.Sprintf(format, item), "PRIVATE") || strings.Contains(fmt.Sprintf(format, item), "private-path") {
			t.Fatal("private normalized item formatted input")
		}
	}
	if _, err := json.Marshal(item); err == nil {
		t.Fatal("private normalized item serialized")
	}
}

func TestValidateFileProfileResource(t *testing.T) {
	for _, profile := range []string{"", "cpra.file.base.v0", "cpra.file.external.v1"} {
		if err := ValidateFileProfileResource(profile, api.Resource{Kind: "Credential"}); !errors.Is(err, ErrUnsupportedNormalization) {
			t.Fatal("unsupported profile was not distinct", err)
		}
	}
	for _, kind := range []string{"Credential", "Recipient", "NotificationGroup"} {
		if err := ValidateFileProfileResource(FileNormalizationProfile, api.Resource{Kind: kind}); err != nil {
			t.Fatal("base resource excluded", kind, err)
		}
	}
	// This helper checks the stable profile projection, not provider settings.
	// Every documented built-in remains available independent of linked drivers.
	for category, drivers := range map[string][]string{
		"check":        {"http", "tcp", "icmp", "dns", "udp", "grpc", "docker", "redis", "postgres", "mysql", "mongo", "rabbitmq", "kafka", "tls"},
		"recovery":     {"kubernetes", "webhook", "systemd", "aws", "docker"},
		"notification": {"email", "webhook", "log", "pagerduty", "slack", "telegram", "discord", "opsgenie", "teams", "mattermost", "pushover", "twilio", "datadog", "victorops"},
	} {
		for _, driver := range drivers {
			t.Run(category+"/"+driver, func(t *testing.T) {
				d := api.DriverConfig{Type: driver, Config: json.RawMessage(`{}`)}
				spec := api.MonitorSpec{Check: api.CheckSpec{Driver: api.DriverConfig{Type: "http"}}}
				switch category {
				case "check":
					spec.Check.Driver = d
				case "recovery":
					spec.Recovery = &api.RecoverySpec{Driver: d}
				case "notification":
					spec.Notifications = &map[string]api.AlertRule{"red": {Driver: &d, NotifyType: &driver}}
				}
				raw, err := json.Marshal(spec)
				if err != nil {
					t.Fatal(err)
				}
				before := bytes.Clone(raw)
				if err := ValidateFileProfileResource(FileNormalizationProfile, api.Resource{Kind: "Monitor", Spec: raw}); err != nil || !bytes.Equal(raw, before) {
					t.Fatal("built-in changed or rejected", err)
				}
				if category == "notification" {
					raw, _ = json.Marshal(d)
					if err := ValidateFileProfileResource(FileNormalizationProfile, api.Resource{Kind: "NotificationEndpoint", Spec: raw}); err != nil {
						t.Fatal(err)
					}
				}
			})
		}
	}
	for _, resource := range []api.Resource{{Kind: "JobType"}, {Kind: "Monitor", Spec: json.RawMessage(`{"PRIVATE-CANARY":`)}, {Kind: "NotificationEndpoint", Spec: json.RawMessage(`{"type":"PRIVATE-CANARY"}`)}} {
		if err := ValidateFileProfileResource(FileNormalizationProfile, resource); err == nil || strings.Contains(err.Error(), "PRIVATE-CANARY") {
			t.Fatal("invalid profile resource accepted or diagnostic echoed its data", err)
		}
	}
}
