// Generated by scripts/dashboard/generate_api.py. Do not edit.
// Wire types preserve presence; validation constraints remain server-authoritative.
// sha256 dashboard/api-generation.json ef5aeada7ee5c8cd93e4c6cb3af85999f08683964e05ef24a32e2c1ca191280e
// sha256 api/openapi/models.base.json 35e2e8f652fa41001a04a75c148f8aa5de3b546d9786a075b64939d880d7c4ea
// sha256 api/openapi/operations.json 42298294454877e9edba7e8850272fbfa4ccab55dc3bc59a215df6538bf5688a
// sha256 api/openapi/contract.base.json c12a05509711f356585219b2c5eab12326ed6dd5098b9d511f28f27168e68a99
// sha256 scripts/dashboard/generate_api.py 30859c8287479c7a490830367ccce0c456c501d9669f673774ad4b4dbc09c51d

export type Duration = string;

export type CodeNotificationEmail = {
  "allowInsecure"?: boolean;
  "to"?: string;
  "from"?: string;
  "server"?: string;
  "subject"?: string;
};

export type CodeNotificationWebhook = {
  "url"?: string;
  "method"?: string;
  "headers"?: {
  [key: string]: string;
};
};

export type InterventionTargetKubernetes = {
  "type"?: string;
  "kubeconfigPath"?: string;
  "namespace"?: string;
  "kind"?: string;
  "name"?: string;
  "replicas"?: number;
  "timeout"?: Duration;
};

export type InterventionTargetWebhook = {
  "type"?: string;
  "url"?: string;
  "method"?: string;
  "headers"?: {
  [key: string]: string;
};
  "body"?: string;
  "timeout"?: Duration;
};

export type InterventionTargetSystemd = {
  "type"?: string;
  "unit"?: string;
  "mode"?: string;
  "timeout"?: Duration;
};

export type InterventionTargetAWS = {
  "type"?: string;
  "region"?: string;
  "operation"?: string;
  "instanceId"?: string;
  "timeout"?: Duration;
};

export type PulseHTTPConfig = {
  "url"?: string;
  "method"?: string;
  "headers"?: {
  [key: string]: string;
};
  "body"?: string;
  "expectedStatus"?: Array<number>;
  "insecureSkipVerify"?: boolean;
  "retries"?: number;
};

export type PulseTCPConfig = {
  "host"?: string;
  "port"?: number;
  "retries"?: number;
};

export type PulseICMPConfig = {
  "host"?: string;
  "ignorePrivilege"?: boolean;
  "count"?: number;
  "retries"?: number;
};

export type PulseDNSConfig = {
  "host"?: string;
  "server"?: string;
  "retries"?: number;
};

export type PulseUDPConfig = {
  "host"?: string;
  "port"?: number;
  "payload"?: string;
  "retries"?: number;
};

export type PulseGRPCConfig = {
  "host"?: string;
  "port"?: number;
  "service"?: string;
  "retries"?: number;
};

export type PulseDockerConfig = {
  "container"?: string;
  "retries"?: number;
};

export type InterventionTargetDocker = {
  "type"?: string;
  "container"?: string;
  "timeout"?: Duration;
};

export type CodeNotificationLog = {
  "file"?: string;
};

export type CodeNotificationPagerDuty = {
  "routingKey"?: string;
  "url"?: string;
};

export type CodeNotificationSlack = {
  "hook"?: string;
};

export type CodeNotificationTelegram = {
  "url"?: string;
  "testMode"?: boolean;
  "botToken"?: string;
  "chatId"?: string;
};

export type CodeNotificationDiscord = {
  "webhookUrl"?: string;
};

export type CodeNotificationOpsgenie = {
  "apiKey"?: string;
  "url"?: string;
};

export type CodeNotificationTeams = {
  "webhookUrl"?: string;
};

export type CodeNotificationMattermost = {
  "webhookUrl"?: string;
  "channel"?: string;
  "username"?: string;
};

export type CodeNotificationPushover = {
  "url"?: string;
  "appToken"?: string;
  "userKey"?: string;
  "title"?: string;
  "priority"?: number;
  "retry"?: number;
  "expire"?: number;
  "sound"?: string;
};

export type CodeNotificationTwilio = {
  "url"?: string;
  "accountSid"?: string;
  "authToken"?: string;
  "from"?: string;
  "to"?: string;
};

export type CodeNotificationDatadog = {
  "url"?: string;
  "apiKey"?: string;
  "appKey"?: string;
  "site"?: string;
  "tags"?: Array<string>;
};

export type CodeNotificationVictorOps = {
  "url"?: string;
  "restEndpointKey"?: string;
  "routingKey"?: string;
  "messageType"?: string;
  "entityId"?: string;
};

export type PulseRedisConfig = {
  "addr"?: string;
  "password"?: string;
  "username"?: string;
  "db"?: number;
  "retries"?: number;
};

export type PulsePostgresConfig = {
  "dsn"?: string;
  "host"?: string;
  "port"?: number;
  "user"?: string;
  "password"?: string;
  "database"?: string;
  "sslmode"?: string;
  "retries"?: number;
};

export type PulseMySQLConfig = {
  "dsn"?: string;
  "host"?: string;
  "port"?: number;
  "user"?: string;
  "password"?: string;
  "database"?: string;
  "retries"?: number;
};

export type PulseMongoConfig = {
  "uri"?: string;
  "retries"?: number;
};

export type PulseRabbitMQConfig = {
  "url"?: string;
  "retries"?: number;
};

export type PulseKafkaConfig = {
  "brokers"?: Array<string>;
  "retries"?: number;
};

export type PulseTLSConfig = {
  "host"?: string;
  "port"?: number;
  "serverName"?: string;
  "warnDays"?: number;
  "criticalDays"?: number;
  "insecureSkipVerify"?: boolean;
  "retries"?: number;
};

export type Metadata = {
  "id": string;
  "uid"?: string;
  "name"?: string;
  "resourceVersion"?: string;
  "generation"?: number;
  "labels"?: {
  [key: string]: string;
};
};

export type Resource = {
  "apiVersion": string;
  "kind": string;
  "metadata": Metadata;
  "spec": unknown;
  "status"?: unknown;
};

export type DriverConfig = {
  "type": string;
  "config": unknown;
  "credentialRefs"?: {
  [key: string]: string;
};
};

export type CheckSpec = {
  "driver": DriverConfig;
  "interval": Duration;
  "timeout": Duration;
  "unhealthyThreshold"?: number;
  "healthyThreshold"?: number;
  "retries"?: number;
  "groups"?: Array<string>;
  "maxFailures"?: number;
};

export type RecoverySpec = {
  "driver": DriverConfig;
  "maxAttempts"?: number;
  "cooldown"?: Duration;
  "retries"?: number;
  "maxFailures"?: number;
};

export type MaintenanceWindow = {
  "start"?: string;
  "end"?: string;
  "cron"?: string;
  "duration"?: Duration;
  "timezone"?: string;
};

export type MonitorSpec = {
  "enabled"?: boolean;
  "check": CheckSpec;
  "recovery"?: RecoverySpec;
  "notificationGroupRefs"?: Array<string>;
  "notifications"?: {
  [key: string]: AlertRule;
};
  "maintenance"?: Array<MaintenanceWindow>;
  "tags"?: Array<string>;
};

export type Measurement = {
  "available": boolean;
  "value"?: number;
  "reason"?: string;
};

export type MonitorStatus = {
  "observedGeneration"?: number;
  "controlRevision"?: string;
  "statusRevision"?: string;
  "executionRevision"?: string;
  "health"?: string;
  "lastCheckedAt"?: string;
  "lastCheckLatencyMs"?: Measurement;
  "snoozedUntil"?: string;
  "incidentID"?: string;
  "unknownActions"?: number;
};

export type Monitor = {
  "apiVersion": string;
  "kind": string;
  "metadata": Metadata;
  "spec": MonitorSpec;
  "status"?: MonitorStatus;
};

export type NotificationEndpoint = {
  "apiVersion": string;
  "kind": string;
  "metadata": Metadata;
  "spec": DriverConfig;
  "status"?: unknown;
};

export type NotificationGroup = {
  "apiVersion": string;
  "kind": string;
  "metadata": Metadata;
  "spec": NotificationGroupSpec;
  "status"?: unknown;
};

export type Credential = {
  "apiVersion": string;
  "kind": string;
  "metadata": Metadata;
  "spec": CredentialSpec;
  "status"?: unknown;
};

export type NotificationGroupSpec = {
  "endpointRefs"?: Array<string>;
  "recipientRefs"?: Array<string>;
};

export type CredentialSpec = {
  /** Write-only input. Never populate from a read response. */
  "value"?: string;
  "description"?: string;
};

export type FieldError = {
  "field": string;
  "reason"?: string;
  "message": string;
};

export type Problem = {
  "type"?: string;
  "title"?: string;
  "status"?: number;
  "detail"?: string;
  "instance"?: string;
  "requestID"?: string;
  "operationID"?: string;
  "code"?: string;
  "errors"?: Array<FieldError>;
};

export type ControlRequest = {
  "revision": string;
  "reason"?: string;
  "note"?: string;
  "duration"?: Duration;
  "incidentID"?: string;
  "evidenceRefs"?: Array<string>;
  "resolution"?: string;
};

export type Action = {
  "id": string;
  "monitorID"?: string;
  "incarnationUID"?: string;
  "incidentID"?: string;
  "state": string;
  "kind"?: string;
  "executionID"?: string;
  "executionRevision"?: string;
  "createdAt"?: string;
  "updatedAt"?: string;
  "reason"?: string;
  "receiptID"?: string;
  "reviewRevision"?: string;
  "held": boolean;
  "executorFenced": boolean;
  "outcome"?: string;
  "review"?: ActionReview;
  "lateEvidence"?: ActionEvidence;
  "conflictingEvidence"?: ActionEvidence;
};

export type Incident = {
  "id": string;
  "monitorID": string;
  "revision": string;
  "state": string;
  "openedAt"?: string;
  "closedAt"?: string;
  "acknowledgedBy"?: string;
  "acknowledgedAt"?: string;
  "dismissed"?: boolean;
};

export type Event = {
  "id": string;
  "monitorID": string;
  "kind": string;
  "time": string;
  "actor"?: string;
  "reason"?: string;
  "actionID"?: string;
  "incidentID"?: string;
  "note"?: string;
  "actionKind"?: string;
  "color"?: string;
  "outcome"?: string;
  "executionRevision"?: string;
  "controlRevision"?: string;
  "endpoint"?: number;
  "evidenceRefs"?: Array<string>;
};

export type ApplyItem = {
  "id": string;
  "contentDigest": string;
  "source": string;
  "resource": Resource;
  "ordinal": number;
  "sourceDocument": number;
  "sourceItem": number;
};

export type ApplyResult = {
  "id": string;
  "outcome": string;
  "oldVersion"?: string;
  "newVersion"?: string;
  "message"?: string;
  "committed"?: boolean;
  "applied"?: boolean;
  "kind"?: string;
  "inputOrdinal"?: number;
  "planOrdinal"?: number;
  "source"?: string;
  "sourceDocument"?: number;
  "sourceItem"?: number;
  "originalUID"?: string;
  "uid"?: string;
  "generation"?: number;
  "catalogDecision"?: string;
  "committedIndex"?: number;
  "decidedAt"?: string;
  "childDisposition"?: ExecutionChildDisposition;
};

export type PreflightRequest = {
  "items": Array<ApplyItem>;
  "identityFormat": "cpra.collection.hmac-sha256-json-bytes.v1";
  /** Write-only input. Never populate from a read response. */
  "identityKey": string;
  /** Write-only input. Never populate from a read response. */
  "sourceFingerprint": string;
  "contentDigest": string;
  "itemCount": number;
};

export type Preflight = {
  "valid": boolean;
  "contentDigest"?: string;
  "items"?: Array<ApplyResult>;
  "errors"?: Array<FieldError>;
  "identityFormat"?: "cpra.collection.hmac-sha256-json-bytes.v1";
  "itemCount"?: number;
};

export type OperationCreateRequest = {
  "contentDigest": string;
  "itemCount": number;
  "identityFormat": "cpra.collection.hmac-sha256-json-bytes.v1";
  /** Write-only input. Never populate from a read response. */
  "identityKey": string;
  /** Write-only input. Never populate from a read response. */
  "sourceFingerprint": string;
  "admissionTicket": string;
  "normalizationProfile"?: string;
};

export type UploadRequest = {
  "items": Array<ApplyItem>;
};

export type Operation = {
  "id": string;
  "state": string;
  "contentDigest": string;
  "items"?: Array<ApplyResult>;
  "nextCursor"?: string;
  "retryAfterSeconds"?: number;
  "committed"?: number;
  "applied"?: number;
  "uploaded"?: number;
  "validated"?: boolean;
  "identityFormat"?: "cpra.collection.hmac-sha256-json-bytes.v1";
  "itemCount"?: number;
  "executionResult"?: ExecutionResultAvailability;
  "normalizationProfile"?: string;
};

export type StorageState = {
  "available": boolean;
  "mode": string;
  "formatVersion"?: number;
  "commitIndex"?: number;
  "appliedIndex"?: number;
  "bytes"?: number;
  "error"?: string;
  "bytesAvailable"?: boolean;
  "commitLatency"?: Measurement;
  "snapshotDuration"?: Measurement;
  "singleNode"?: boolean;
};

export type State = {
  "generatedAt": string;
  "ready": boolean;
  "live": boolean;
  "storage": StorageState;
  "projectionAgeMs"?: number;
  "unknownActions"?: number;
  "actions"?: Array<Action>;
  "projectionAvailable"?: boolean;
  "projectionFresh"?: boolean;
  "unknownActionsAvailable"?: boolean;
  "controllerAvailable"?: boolean;
  "controllerReady"?: boolean;
  "controllerReason"?: string;
  "readinessReason"?: string;
};

export type Queue = {
  "name": string;
  "depth": number;
  "capacity": number;
  "oldestPendingMs"?: Measurement;
  "enqueuedPerSecond"?: number;
  "completedPerSecond"?: number;
  "drops"?: number;
  "saturated": boolean;
  "limitReason"?: string;
  "available"?: boolean;
  "ratesAvailable"?: boolean;
  "dequeuedPerSecond"?: number;
  "completedRateAvailable"?: boolean;
  "utilization"?: Measurement;
  "averageWait"?: Measurement;
  "maximumWait"?: Measurement;
  "sampleWindow"?: Duration;
};

export type Pool = {
  "name": string;
  "workers": number;
  "minimum"?: number;
  "maximum"?: number;
  "busy"?: number;
  "modelRecommendation"?: number;
  "adjustmentReason"?: string;
  "available"?: boolean;
  "capacity"?: number;
  "target"?: number;
  "pendingResults"?: number;
  "waitingTasks"?: number;
  "tasksSubmitted"?: number;
  "tasksCompleted"?: number;
  "scalingEvents"?: number;
  "busyAvailable"?: boolean;
  "modelRecommendationAvailable"?: boolean;
  "sizingModel"?: string;
  "sloCondition"?: string;
  "lastScaleAt"?: string;
  "serviceTime"?: Measurement;
  "serviceSamples"?: number;
};

export type System = {
  "name": string;
  "updates"?: number;
  "entitiesProcessed"?: number;
  "lastUpdateDurationMs"?: Measurement;
  "progressAt"?: string;
  "available"?: boolean;
  "averageUpdateDuration"?: Measurement;
  "maximumUpdateDuration"?: Measurement;
  "minimumUpdateDuration"?: Measurement;
};

export type Percentiles = {
  "available": boolean;
  "p50Ms"?: number;
  "p95Ms"?: number;
  "p99Ms"?: number;
};

export type SLOReport = {
  "pipeline": string;
  "driver": string;
  "samples": number;
  "missed"?: number;
  "timeouts"?: number;
  "queueDelay"?: Percentiles;
  "execution"?: Percentiles;
  "totalLatency"?: Percentiles;
  "queueThresholdPassed"?: number;
  "totalThresholdPassed"?: number;
  "attainment"?: Measurement;
  "condition"?: string;
  "expected"?: number;
  "overdue"?: number;
  "pending"?: number;
  "queueAttainment"?: Measurement;
  "resultAttainment"?: Measurement;
  "pausedMonitors"?: number;
  "pausedMonitorSeconds"?: number;
};

export type SLOView = {
  "generatedAt": string;
  "window": Duration;
  "coverageGap": boolean;
  "reports": Array<SLOReport>;
  "available"?: boolean;
  "queueTargetMs"?: number;
  "resultTargetMs"?: number;
  "gapStart"?: string;
  "gapEnd"?: string;
};

export type Metrics = {
  "generatedAt": string;
  "queues"?: Array<Queue>;
  "pools"?: Array<Pool>;
  "systems"?: Array<System>;
  "slo"?: SLOView;
  "queuesAvailable"?: boolean;
  "poolsAvailable"?: boolean;
  "systemsAvailable"?: boolean;
};

export type RuntimeConfig = {
  "storageMode"?: string;
  "historyRetention"?: Duration;
  "queueCapacity"?: number;
  "readOnly"?: boolean;
  "sloWindow"?: Duration;
  "available"?: boolean;
  "queueTarget"?: Duration;
  "resultTarget"?: Duration;
};

export type Health = {
  "available": boolean;
  "reason"?: string;
  "generatedAt"?: string;
};

export type Capabilities = {
  "apiVersions": Array<string>;
  "drivers": {
  [key: string]: Array<string>;
};
  "resources": Array<string>;
  "patchTypes": Array<string>;
  "resourceOperations"?: {
  [key: string]: Array<string>;
};
};

export type Version = {
  "version": string;
  "commit"?: string;
  "sourceTime"?: string;
  "goVersion"?: string;
  "storageFormat"?: number;
};

export type Explanation = {
  "resource": string;
  "description": string;
  "schema": unknown;
};

export type MonitorList = {
  "items": Array<Monitor>;
  "nextCursor"?: string;
  "snapshot"?: string;
  "generatedAt"?: string;
};

export type NotificationEndpointList = {
  "items": Array<NotificationEndpoint>;
  "nextCursor"?: string;
  "snapshot"?: string;
  "generatedAt"?: string;
};

export type NotificationGroupList = {
  "items": Array<NotificationGroup>;
  "nextCursor"?: string;
  "snapshot"?: string;
  "generatedAt"?: string;
};

export type CredentialList = {
  "items": Array<Credential>;
  "nextCursor"?: string;
  "snapshot"?: string;
  "generatedAt"?: string;
};

export type IncidentList = {
  "items": Array<Incident>;
  "nextCursor"?: string;
  "snapshot"?: string;
  "generatedAt"?: string;
};

export type ActionList = {
  "items": Array<Action>;
  "nextCursor"?: string;
  "snapshot"?: string;
  "generatedAt"?: string;
};

export type EventList = {
  "items": Array<Event>;
  "nextCursor"?: string;
  "snapshot"?: string;
  "generatedAt"?: string;
};

export type QueueList = {
  "items": Array<Queue>;
  "nextCursor"?: string;
  "snapshot"?: string;
  "generatedAt"?: string;
  "available"?: boolean;
};

export type PoolList = {
  "items": Array<Pool>;
  "nextCursor"?: string;
  "snapshot"?: string;
  "generatedAt"?: string;
  "available"?: boolean;
};

export type SystemList = {
  "items": Array<System>;
  "nextCursor"?: string;
  "snapshot"?: string;
  "generatedAt"?: string;
  "available"?: boolean;
};

export type MergePatch = unknown;

export type AlertRule = {
  "dispatch"?: boolean;
  "endpointRefs"?: Array<string>;
  "groupRef"?: string;
  "driver"?: DriverConfig;
  "notifyType"?: string;
  "recipientRefs"?: Array<string>;
};

export type RecipientSpec = {
  "endpointRefs": Array<string>;
};

export type Recipient = {
  "apiVersion": string;
  "kind": string;
  "metadata": Metadata;
  "spec": RecipientSpec;
  "status"?: unknown;
};

export type RecipientList = {
  "items": Array<Recipient>;
  "nextCursor"?: string;
  "snapshot"?: string;
  "generatedAt"?: string;
};

export type AccessInfo = {
  "principalId": string;
  "role": string;
  "permissions": Array<string>;
};

export type OperationList = {
  "items": Array<Operation>;
  "nextCursor"?: string;
  "snapshot"?: string;
  "generatedAt"?: string;
};

export type ActionReview = {
  "revision": string;
  "resolution": "accepted" | "rejected" | "inconclusive";
  "actor": string;
  "reviewedAt": string;
  "reason": string;
  "note"?: string;
  "evidenceRefs"?: Array<string>;
  "conflict"?: boolean;
};

export type ActionEvidence = {
  "outcome": string;
  "executionStart": string;
  "executionEnd": string;
  "recordedAt": string;
};

export type CollectionPrepareRequest = {
  "contentDigest": string;
  "itemCount": number;
  "identityFormat": "cpra.collection.hmac-sha256-json-bytes.v1";
  /** Write-only input. Never populate from a read response. */
  "identityKey": string;
  /** Write-only input. Never populate from a read response. */
  "sourceFingerprint": string;
  "normalizationProfile"?: string;
};

export type CollectionAdmission = {
  "ticket": string;
  "expiresAt": string;
};

export type ValidationResultItem = {
  "ordinal": number;
  "kind": string;
  "id": string;
  "source": string;
  "sourceDocument": number;
  "sourceItem": number;
  "change"?: string;
  "issue"?: string;
  "uid"?: string;
  "resourceVersion"?: string;
};

export type ValidationResultSummary = {
  "resultID": string;
  "valid": boolean;
  "issue"?: string;
  "summaryOnly": boolean;
  "count": number;
  "digest": string;
  "planID"?: string;
  "planDigest"?: string;
  "capabilitiesDigest": string;
  "finalizedAt": string;
  "expiresAt": string;
};

export type ValidationResultPage = {
  "operationID": string;
  "identityFormat": string;
  "contentDigest": string;
  "itemCount": number;
  "summary": ValidationResultSummary;
  "items": Array<ValidationResultItem>;
  "nextCursor"?: string;
};

export type ExecutionResultCounts = {
  "processed": number;
  "accepted": number;
  "unchanged": number;
  "conflicts": number;
  "dependencyBlocked": number;
  "unattempted": number;
  "childPending": number;
  "childApplied": number;
  "childFailed": number;
  "childSuperseded": number;
  "childInvalidated": number;
};

export type ExecutionResultSummary = {
  "resultID": string;
  "uploadID": string;
  "planID": string;
  "planDigest": string;
  "outcome": string;
  "itemCount": number;
  "processed": number;
  "accepted": number;
  "unchanged": number;
  "conflicts": number;
  "dependencyBlocked": number;
  "unattempted": number;
  "childPending": number;
  "childApplied": number;
  "childFailed": number;
  "childSuperseded": number;
  "childInvalidated": number;
  "finalizedAt": string;
  "expiresAt": string;
  "bytes": number;
  "digest": string;
};

export type ExecutionResultAvailability = {
  "state": string;
  "counts"?: ExecutionResultCounts;
  "summary"?: ExecutionResultSummary;
};

export type ExecutionChildDisposition = {
  "operationID": string;
  "state": string;
  "outcome"?: string;
  "updatedAt"?: string;
  "invalidatedByRestore"?: string;
};

export type CollectionReselectionCreateRequest = {
  "sourceCount": number;
  "normalizationProfile": string;
};

export type CollectionReselectionAttempt = {
  "id": string;
  "operationID": string;
  "normalizationProfile": string;
  "phase": "uploading" | "verifying" | "verified" | "transferring" | "completed" | "failed";
  "sourceCount": number;
  "sourcesCompleted": number;
  "rawBytes": number;
  "nextSource": number;
  "nextOffset": number;
  "expiresAt": string;
  "errorCode"?: "input_mismatch" | "authorization_changed" | "operation_changed" | "expired" | "storage_unavailable" | "quota_exceeded" | "verification_failed" | "transfer_failed";
  "operationUploaded": number;
};

export const operationContracts = {
  "AcknowledgeIncident": {
    "cas": true,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/incidents/{id}/acknowledge"
  },
  "ActivateOperation": {
    "cas": false,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/operations/{id}/activate"
  },
  "CancelOperation": {
    "cas": false,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/operations/{id}/cancel"
  },
  "CreateCollectionReselection": {
    "cas": false,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/operations/{id}/reselection"
  },
  "CreateCredential": {
    "cas": false,
    "createOnly": true,
    "method": "POST",
    "path": "/api/v2/credentials"
  },
  "CreateMonitor": {
    "cas": false,
    "createOnly": true,
    "method": "POST",
    "path": "/api/v2/monitors"
  },
  "CreateNotificationEndpoint": {
    "cas": false,
    "createOnly": true,
    "method": "POST",
    "path": "/api/v2/notification-endpoints"
  },
  "CreateNotificationGroup": {
    "cas": false,
    "createOnly": true,
    "method": "POST",
    "path": "/api/v2/notification-groups"
  },
  "CreateOperation": {
    "cas": false,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/operations"
  },
  "CreateRecipient": {
    "cas": false,
    "createOnly": true,
    "method": "POST",
    "path": "/api/v2/recipients"
  },
  "DeleteCredential": {
    "cas": true,
    "createOnly": false,
    "method": "DELETE",
    "path": "/api/v2/credentials/{id}"
  },
  "DeleteMonitor": {
    "cas": true,
    "createOnly": false,
    "method": "DELETE",
    "path": "/api/v2/monitors/{id}"
  },
  "DeleteNotificationEndpoint": {
    "cas": true,
    "createOnly": false,
    "method": "DELETE",
    "path": "/api/v2/notification-endpoints/{id}"
  },
  "DeleteNotificationGroup": {
    "cas": true,
    "createOnly": false,
    "method": "DELETE",
    "path": "/api/v2/notification-groups/{id}"
  },
  "DeleteRecipient": {
    "cas": true,
    "createOnly": false,
    "method": "DELETE",
    "path": "/api/v2/recipients/{id}"
  },
  "DiscardCollectionReselection": {
    "cas": false,
    "createOnly": false,
    "method": "DELETE",
    "path": "/api/v2/operations/{id}/reselection/{attempt}"
  },
  "DismissIncident": {
    "cas": true,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/incidents/{id}/dismiss"
  },
  "ExplainResource": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/schemas/{id}"
  },
  "GetAccess": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/self"
  },
  "GetAction": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/actions/{id}"
  },
  "GetCapabilities": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/discovery"
  },
  "GetCollectionReselection": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/operations/{id}/reselection/{attempt}"
  },
  "GetConfig": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/config"
  },
  "GetCredential": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/credentials/{id}"
  },
  "GetHistory": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/history"
  },
  "GetIncident": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/incidents/{id}"
  },
  "GetLive": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/healthz"
  },
  "GetMetrics": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/metrics"
  },
  "GetMonitor": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/monitors/{id}"
  },
  "GetNotificationEndpoint": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/notification-endpoints/{id}"
  },
  "GetNotificationGroup": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/notification-groups/{id}"
  },
  "GetOperation": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/operations/{id}"
  },
  "GetOperationValidation": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/operations/{id}/validation"
  },
  "GetPools": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/pools"
  },
  "GetQueues": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/queues"
  },
  "GetReady": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/readyz"
  },
  "GetRecipient": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/recipients/{id}"
  },
  "GetSLO": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/slo"
  },
  "GetState": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/state"
  },
  "GetSystems": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/systems"
  },
  "GetVersion": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/version"
  },
  "ListActions": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/actions"
  },
  "ListCredentials": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/credentials"
  },
  "ListIncidents": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/incidents"
  },
  "ListMonitors": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/monitors"
  },
  "ListNotificationEndpoints": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/notification-endpoints"
  },
  "ListNotificationGroups": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/notification-groups"
  },
  "ListOperations": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/operations"
  },
  "ListRecipients": {
    "cas": false,
    "createOnly": false,
    "method": "GET",
    "path": "/api/v2/recipients"
  },
  "PatchCredential": {
    "cas": true,
    "createOnly": false,
    "method": "PATCH",
    "path": "/api/v2/credentials/{id}"
  },
  "PatchMonitor": {
    "cas": true,
    "createOnly": false,
    "method": "PATCH",
    "path": "/api/v2/monitors/{id}"
  },
  "PatchNotificationEndpoint": {
    "cas": true,
    "createOnly": false,
    "method": "PATCH",
    "path": "/api/v2/notification-endpoints/{id}"
  },
  "PatchNotificationGroup": {
    "cas": true,
    "createOnly": false,
    "method": "PATCH",
    "path": "/api/v2/notification-groups/{id}"
  },
  "PatchRecipient": {
    "cas": true,
    "createOnly": false,
    "method": "PATCH",
    "path": "/api/v2/recipients/{id}"
  },
  "PreflightCollection": {
    "cas": false,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/collections/preflight"
  },
  "PrepareCollection": {
    "cas": false,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/collections/prepare"
  },
  "RecoverMonitor": {
    "cas": true,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/monitors/{id}/recover"
  },
  "ReopenIncident": {
    "cas": true,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/incidents/{id}/reopen"
  },
  "ReplaceCredential": {
    "cas": true,
    "createOnly": false,
    "method": "PUT",
    "path": "/api/v2/credentials/{id}"
  },
  "ReplaceMonitor": {
    "cas": true,
    "createOnly": false,
    "method": "PUT",
    "path": "/api/v2/monitors/{id}"
  },
  "ReplaceNotificationEndpoint": {
    "cas": true,
    "createOnly": false,
    "method": "PUT",
    "path": "/api/v2/notification-endpoints/{id}"
  },
  "ReplaceNotificationGroup": {
    "cas": true,
    "createOnly": false,
    "method": "PUT",
    "path": "/api/v2/notification-groups/{id}"
  },
  "ReplaceRecipient": {
    "cas": true,
    "createOnly": false,
    "method": "PUT",
    "path": "/api/v2/recipients/{id}"
  },
  "ResumeCollectionReselection": {
    "cas": false,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/operations/{id}/reselection/{attempt}/resume"
  },
  "ReviewAction": {
    "cas": true,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/actions/{id}/review"
  },
  "SnoozeMonitor": {
    "cas": true,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/monitors/{id}/snooze"
  },
  "UnsnoozeMonitor": {
    "cas": true,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/monitors/{id}/unsnooze"
  },
  "UploadCollectionReselectionSource": {
    "cas": false,
    "createOnly": false,
    "method": "PUT",
    "path": "/api/v2/operations/{id}/reselection/{attempt}/sources/{source}"
  },
  "UploadOperation": {
    "cas": false,
    "createOnly": false,
    "method": "PUT",
    "path": "/api/v2/operations/{id}/items"
  },
  "ValidateOperation": {
    "cas": false,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/operations/{id}/validate"
  },
  "VerifyCollectionReselection": {
    "cas": false,
    "createOnly": false,
    "method": "POST",
    "path": "/api/v2/operations/{id}/reselection/{attempt}/verify"
  }
} as const;

export const notificationFields = {
  "email": [
    {
      "key": "allowInsecure",
      "label": "Allow insecure",
      "type": "boolean",
      "protected": false
    },
    {
      "key": "to",
      "label": "To",
      "type": "string",
      "protected": false
    },
    {
      "key": "from",
      "label": "From",
      "type": "string",
      "protected": false
    },
    {
      "key": "server",
      "label": "Server",
      "type": "string",
      "protected": true
    },
    {
      "key": "subject",
      "label": "Subject",
      "type": "string",
      "protected": false
    }
  ],
  "webhook": [
    {
      "key": "url",
      "label": "Url",
      "type": "string",
      "protected": true
    },
    {
      "key": "method",
      "label": "Method",
      "type": "string",
      "protected": false
    },
    {
      "key": "headers",
      "label": "Headers",
      "type": "string-map",
      "protected": true
    }
  ],
  "log": [
    {
      "key": "file",
      "label": "File",
      "type": "string",
      "protected": false
    }
  ],
  "pagerduty": [
    {
      "key": "routingKey",
      "label": "Routing key",
      "type": "string",
      "protected": true
    },
    {
      "key": "url",
      "label": "Url",
      "type": "string",
      "protected": true
    }
  ],
  "slack": [
    {
      "key": "hook",
      "label": "Hook",
      "type": "string",
      "protected": true
    }
  ],
  "telegram": [
    {
      "key": "url",
      "label": "Url",
      "type": "string",
      "protected": true
    },
    {
      "key": "testMode",
      "label": "Test mode",
      "type": "boolean",
      "protected": false
    },
    {
      "key": "botToken",
      "label": "Bot token",
      "type": "string",
      "protected": true
    },
    {
      "key": "chatId",
      "label": "Chat id",
      "type": "string",
      "protected": false
    }
  ],
  "discord": [
    {
      "key": "webhookUrl",
      "label": "Webhook url",
      "type": "string",
      "protected": true
    }
  ],
  "opsgenie": [
    {
      "key": "apiKey",
      "label": "Api key",
      "type": "string",
      "protected": true
    },
    {
      "key": "url",
      "label": "Url",
      "type": "string",
      "protected": true
    }
  ],
  "teams": [
    {
      "key": "webhookUrl",
      "label": "Webhook url",
      "type": "string",
      "protected": true
    }
  ],
  "mattermost": [
    {
      "key": "webhookUrl",
      "label": "Webhook url",
      "type": "string",
      "protected": true
    },
    {
      "key": "channel",
      "label": "Channel",
      "type": "string",
      "protected": false
    },
    {
      "key": "username",
      "label": "Username",
      "type": "string",
      "protected": false
    }
  ],
  "pushover": [
    {
      "key": "url",
      "label": "Url",
      "type": "string",
      "protected": true
    },
    {
      "key": "appToken",
      "label": "App token",
      "type": "string",
      "protected": true
    },
    {
      "key": "userKey",
      "label": "User key",
      "type": "string",
      "protected": true
    },
    {
      "key": "title",
      "label": "Title",
      "type": "string",
      "protected": false
    },
    {
      "key": "priority",
      "label": "Priority",
      "type": "number",
      "protected": false
    },
    {
      "key": "retry",
      "label": "Retry",
      "type": "number",
      "protected": false
    },
    {
      "key": "expire",
      "label": "Expire",
      "type": "number",
      "protected": false
    },
    {
      "key": "sound",
      "label": "Sound",
      "type": "string",
      "protected": false
    }
  ],
  "twilio": [
    {
      "key": "url",
      "label": "Url",
      "type": "string",
      "protected": true
    },
    {
      "key": "accountSid",
      "label": "Account sid",
      "type": "string",
      "protected": true
    },
    {
      "key": "authToken",
      "label": "Auth token",
      "type": "string",
      "protected": true
    },
    {
      "key": "from",
      "label": "From",
      "type": "string",
      "protected": false
    },
    {
      "key": "to",
      "label": "To",
      "type": "string",
      "protected": false
    }
  ],
  "datadog": [
    {
      "key": "url",
      "label": "Url",
      "type": "string",
      "protected": true
    },
    {
      "key": "apiKey",
      "label": "Api key",
      "type": "string",
      "protected": true
    },
    {
      "key": "appKey",
      "label": "App key",
      "type": "string",
      "protected": true
    },
    {
      "key": "site",
      "label": "Site",
      "type": "string",
      "protected": false
    },
    {
      "key": "tags",
      "label": "Tags",
      "type": "string-list",
      "protected": false
    }
  ],
  "victorops": [
    {
      "key": "url",
      "label": "Url",
      "type": "string",
      "protected": true
    },
    {
      "key": "restEndpointKey",
      "label": "Rest endpoint key",
      "type": "string",
      "protected": true
    },
    {
      "key": "routingKey",
      "label": "Routing key",
      "type": "string",
      "protected": true
    },
    {
      "key": "messageType",
      "label": "Message type",
      "type": "string",
      "protected": false
    },
    {
      "key": "entityId",
      "label": "Entity id",
      "type": "string",
      "protected": false
    }
  ]
} as const;

export const checkFields = {
  "http": [
    {
      "key": "url",
      "label": "Url",
      "type": "string",
      "protected": false
    },
    {
      "key": "method",
      "label": "Method",
      "type": "string",
      "protected": false
    },
    {
      "key": "headers",
      "label": "Headers",
      "type": "string-map",
      "protected": true
    },
    {
      "key": "body",
      "label": "Body",
      "type": "string",
      "protected": true
    },
    {
      "key": "expectedStatus",
      "label": "Expected status",
      "type": "number-list",
      "protected": false
    },
    {
      "key": "insecureSkipVerify",
      "label": "Insecure skip verify",
      "type": "boolean",
      "protected": false
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ],
  "tcp": [
    {
      "key": "host",
      "label": "Host",
      "type": "string",
      "protected": false
    },
    {
      "key": "port",
      "label": "Port",
      "type": "number",
      "protected": false
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ],
  "icmp": [
    {
      "key": "host",
      "label": "Host",
      "type": "string",
      "protected": false
    },
    {
      "key": "ignorePrivilege",
      "label": "Ignore privilege",
      "type": "boolean",
      "protected": false
    },
    {
      "key": "count",
      "label": "Count",
      "type": "number",
      "protected": false
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ],
  "dns": [
    {
      "key": "host",
      "label": "Host",
      "type": "string",
      "protected": false
    },
    {
      "key": "server",
      "label": "Server",
      "type": "string",
      "protected": false
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ],
  "udp": [
    {
      "key": "host",
      "label": "Host",
      "type": "string",
      "protected": false
    },
    {
      "key": "port",
      "label": "Port",
      "type": "number",
      "protected": false
    },
    {
      "key": "payload",
      "label": "Payload",
      "type": "string",
      "protected": false
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ],
  "grpc": [
    {
      "key": "host",
      "label": "Host",
      "type": "string",
      "protected": false
    },
    {
      "key": "port",
      "label": "Port",
      "type": "number",
      "protected": false
    },
    {
      "key": "service",
      "label": "Service",
      "type": "string",
      "protected": false
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ],
  "docker": [
    {
      "key": "container",
      "label": "Container",
      "type": "string",
      "protected": false
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ],
  "redis": [
    {
      "key": "addr",
      "label": "Addr",
      "type": "string",
      "protected": false
    },
    {
      "key": "password",
      "label": "Password",
      "type": "string",
      "protected": true
    },
    {
      "key": "username",
      "label": "Username",
      "type": "string",
      "protected": false
    },
    {
      "key": "db",
      "label": "Db",
      "type": "number",
      "protected": false
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ],
  "postgres": [
    {
      "key": "dsn",
      "label": "Dsn",
      "type": "string",
      "protected": true
    },
    {
      "key": "host",
      "label": "Host",
      "type": "string",
      "protected": false
    },
    {
      "key": "port",
      "label": "Port",
      "type": "number",
      "protected": false
    },
    {
      "key": "user",
      "label": "User",
      "type": "string",
      "protected": false
    },
    {
      "key": "password",
      "label": "Password",
      "type": "string",
      "protected": true
    },
    {
      "key": "database",
      "label": "Database",
      "type": "string",
      "protected": false
    },
    {
      "key": "sslmode",
      "label": "Sslmode",
      "type": "string",
      "protected": false
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ],
  "mysql": [
    {
      "key": "dsn",
      "label": "Dsn",
      "type": "string",
      "protected": true
    },
    {
      "key": "host",
      "label": "Host",
      "type": "string",
      "protected": false
    },
    {
      "key": "port",
      "label": "Port",
      "type": "number",
      "protected": false
    },
    {
      "key": "user",
      "label": "User",
      "type": "string",
      "protected": false
    },
    {
      "key": "password",
      "label": "Password",
      "type": "string",
      "protected": true
    },
    {
      "key": "database",
      "label": "Database",
      "type": "string",
      "protected": false
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ],
  "mongo": [
    {
      "key": "uri",
      "label": "Uri",
      "type": "string",
      "protected": true
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ],
  "rabbitmq": [
    {
      "key": "url",
      "label": "Url",
      "type": "string",
      "protected": true
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ],
  "kafka": [
    {
      "key": "brokers",
      "label": "Brokers",
      "type": "string-list",
      "protected": false
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ],
  "tls": [
    {
      "key": "host",
      "label": "Host",
      "type": "string",
      "protected": false
    },
    {
      "key": "port",
      "label": "Port",
      "type": "number",
      "protected": false
    },
    {
      "key": "serverName",
      "label": "Server name",
      "type": "string",
      "protected": false
    },
    {
      "key": "warnDays",
      "label": "Warn days",
      "type": "number",
      "protected": false
    },
    {
      "key": "criticalDays",
      "label": "Critical days",
      "type": "number",
      "protected": false
    },
    {
      "key": "insecureSkipVerify",
      "label": "Insecure skip verify",
      "type": "boolean",
      "protected": false
    },
    {
      "key": "retries",
      "label": "Retries",
      "type": "number",
      "protected": false
    }
  ]
} as const;

export const recoveryFields = {
  "kubernetes": [
    {
      "key": "type",
      "label": "Type",
      "type": "string",
      "protected": false
    },
    {
      "key": "kubeconfigPath",
      "label": "Kubeconfig path",
      "type": "string",
      "protected": false
    },
    {
      "key": "namespace",
      "label": "Namespace",
      "type": "string",
      "protected": false
    },
    {
      "key": "kind",
      "label": "Kind",
      "type": "string",
      "protected": false
    },
    {
      "key": "name",
      "label": "Kubernetes resource name",
      "type": "string",
      "protected": false
    },
    {
      "key": "replicas",
      "label": "Replicas",
      "type": "number",
      "protected": false
    },
    {
      "key": "timeout",
      "label": "Timeout",
      "type": "duration",
      "protected": false
    }
  ],
  "webhook": [
    {
      "key": "type",
      "label": "Type",
      "type": "string",
      "protected": false
    },
    {
      "key": "url",
      "label": "Url",
      "type": "string",
      "protected": true
    },
    {
      "key": "method",
      "label": "Method",
      "type": "string",
      "protected": false
    },
    {
      "key": "headers",
      "label": "Headers",
      "type": "string-map",
      "protected": true
    },
    {
      "key": "body",
      "label": "Body",
      "type": "string",
      "protected": true
    },
    {
      "key": "timeout",
      "label": "Timeout",
      "type": "duration",
      "protected": false
    }
  ],
  "systemd": [
    {
      "key": "type",
      "label": "Type",
      "type": "string",
      "protected": false
    },
    {
      "key": "unit",
      "label": "Unit",
      "type": "string",
      "protected": false
    },
    {
      "key": "mode",
      "label": "Mode",
      "type": "string",
      "protected": false
    },
    {
      "key": "timeout",
      "label": "Timeout",
      "type": "duration",
      "protected": false
    }
  ],
  "aws": [
    {
      "key": "type",
      "label": "Type",
      "type": "string",
      "protected": false
    },
    {
      "key": "region",
      "label": "Region",
      "type": "string",
      "protected": false
    },
    {
      "key": "operation",
      "label": "Operation",
      "type": "string",
      "protected": false
    },
    {
      "key": "instanceId",
      "label": "Instance id",
      "type": "string",
      "protected": false
    },
    {
      "key": "timeout",
      "label": "Timeout",
      "type": "duration",
      "protected": false
    }
  ],
  "docker": [
    {
      "key": "type",
      "label": "Type",
      "type": "string",
      "protected": false
    },
    {
      "key": "container",
      "label": "Container",
      "type": "string",
      "protected": false
    },
    {
      "key": "timeout",
      "label": "Timeout",
      "type": "duration",
      "protected": false
    }
  ]
} as const;

export const monitorShapes = {
  "AlertRule": {
    "additionalProperties": false,
    "properties": {
      "dispatch": {
        "type": "boolean"
      },
      "driver": {
        "$ref": "#/components/schemas/DriverConfig"
      },
      "endpointRefs": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "groupRef": {
        "type": "string"
      },
      "notifyType": {
        "description": "Actual notification driver key selected by the Code. Requires recipientRefs or groupRef, and excludes inline driver and direct endpointRefs.",
        "minLength": 1,
        "type": "string"
      },
      "recipientRefs": {
        "items": {
          "minLength": 1,
          "type": "string"
        },
        "type": "array",
        "uniqueItems": true
      }
    },
    "type": "object"
  },
  "CheckSpec": {
    "additionalProperties": false,
    "properties": {
      "driver": {
        "$ref": "#/components/schemas/DriverConfig"
      },
      "groups": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "healthyThreshold": {
        "format": "int64",
        "type": "integer"
      },
      "interval": {
        "$ref": "#/components/schemas/Duration"
      },
      "maxFailures": {
        "format": "int64",
        "type": "integer"
      },
      "retries": {
        "format": "int64",
        "type": "integer"
      },
      "timeout": {
        "$ref": "#/components/schemas/Duration"
      },
      "unhealthyThreshold": {
        "format": "int64",
        "type": "integer"
      }
    },
    "required": [
      "driver",
      "interval",
      "timeout"
    ],
    "type": "object"
  },
  "Duration": {
    "description": "Go duration string, e.g. 60s. Never numeric nanoseconds or ISO-8601.",
    "type": "string",
    "x-go-type": "string"
  },
  "MaintenanceWindow": {
    "additionalProperties": false,
    "properties": {
      "cron": {
        "type": "string"
      },
      "duration": {
        "$ref": "#/components/schemas/Duration"
      },
      "end": {
        "format": "date-time",
        "type": "string"
      },
      "start": {
        "format": "date-time",
        "type": "string"
      },
      "timezone": {
        "type": "string"
      }
    },
    "required": [],
    "type": "object"
  },
  "Measurement": {
    "additionalProperties": false,
    "properties": {
      "available": {
        "type": "boolean"
      },
      "reason": {
        "type": "string",
        "x-go-type-skip-optional-pointer": true
      },
      "value": {
        "description": "Meaningful only when available is true; units are defined by the containing field.",
        "format": "double",
        "type": "number",
        "x-go-type-skip-optional-pointer": true,
        "x-omitempty": false
      }
    },
    "required": [
      "available"
    ],
    "type": "object"
  },
  "MonitorSpec": {
    "additionalProperties": false,
    "properties": {
      "check": {
        "$ref": "#/components/schemas/CheckSpec"
      },
      "enabled": {
        "type": "boolean"
      },
      "maintenance": {
        "items": {
          "$ref": "#/components/schemas/MaintenanceWindow"
        },
        "type": "array"
      },
      "notificationGroupRefs": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "notifications": {
        "additionalProperties": {
          "$ref": "#/components/schemas/AlertRule"
        },
        "type": "object"
      },
      "recovery": {
        "$ref": "#/components/schemas/RecoverySpec"
      },
      "tags": {
        "items": {
          "type": "string"
        },
        "type": "array"
      }
    },
    "required": [
      "check"
    ],
    "type": "object"
  },
  "MonitorStatus": {
    "additionalProperties": false,
    "properties": {
      "controlRevision": {
        "type": "string",
        "x-go-type-skip-optional-pointer": true
      },
      "executionRevision": {
        "type": "string",
        "x-go-type-skip-optional-pointer": true
      },
      "health": {
        "type": "string",
        "x-go-type-skip-optional-pointer": true
      },
      "incidentID": {
        "type": "string",
        "x-go-name": "IncidentID",
        "x-go-type-skip-optional-pointer": true
      },
      "lastCheckLatencyMs": {
        "$ref": "#/components/schemas/Measurement",
        "x-go-name": "LastCheckLatencyMS",
        "x-go-type-skip-optional-pointer": true
      },
      "lastCheckedAt": {
        "format": "date-time",
        "type": "string",
        "x-go-type-skip-optional-pointer": true
      },
      "observedGeneration": {
        "format": "int64",
        "type": "integer",
        "x-go-type-skip-optional-pointer": true
      },
      "snoozedUntil": {
        "format": "date-time",
        "type": "string",
        "x-go-type-skip-optional-pointer": true
      },
      "statusRevision": {
        "type": "string",
        "x-go-type-skip-optional-pointer": true
      },
      "unknownActions": {
        "format": "int64",
        "type": "integer",
        "x-go-type-skip-optional-pointer": true
      }
    },
    "required": [],
    "type": "object"
  },
  "RecoverySpec": {
    "additionalProperties": false,
    "properties": {
      "cooldown": {
        "$ref": "#/components/schemas/Duration"
      },
      "driver": {
        "$ref": "#/components/schemas/DriverConfig"
      },
      "maxAttempts": {
        "format": "int64",
        "type": "integer"
      },
      "maxFailures": {
        "format": "int64",
        "type": "integer"
      },
      "retries": {
        "format": "int64",
        "type": "integer"
      }
    },
    "required": [
      "driver"
    ],
    "type": "object"
  }
} as const;
